// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: 96cac75c4331fbb349a1d9a77f45ac1d99de5c0170b71ad2e8c90d19a314af8d
const uint kRtInstanceMetadataCapacity = 20u;
const uint kRtStaticAssetCapacity = 8u;
const uint kRtPrimitiveMetadataCapacity = 32u;
const uint kRtMaterialCapacity = 32u;
const uint kRtTextureLayerCapacity = 16u;

const uint kRtInstanceFlagStaticPbr = 1u;
const uint kRtInstanceFlagEmissive = 2u;
const uint kRtInstanceFlagTransmissive = 4u;
const uint kRtMaterialFlagDoubleSided = 1u;
const uint kRtMaterialFlagAlpha = 2u;
const uint kRtMaterialFlagTransmission = 4u;
const uint kRtMaterialFlagBaseColorTexture = 8u;
const uint kRtMaterialFlagNormalTexture = 16u;
const uint kRtMaterialFlagOrmTexture = 32u;
const uint kRtMaterialFlagEmissiveTexture = 64u;

struct StaticRtVertex
{
    vec4 position;
    vec4 normal;
    vec4 tangent;
    vec4 uv0;
};
struct RtInstanceMetadata
{
    uint primitiveBase;
    uint primitiveCount;
    uint stableObjectId;
    uint flags;
    uint emitterIndex;
    uint assetIndex;
    uint reserved0;
    uint reserved1;
};
struct RtPrimitiveMetadata
{
    uint vertexOffset;
    uint indexOffset;
    uint indexCount;
    uint materialIndex;
};
struct RtMaterialGpu
{
    vec4 baseColorFactor;
    vec4 emissiveFactorStrength;
    vec4 metallicRoughnessOcclusionTransmission;
    vec4 iorThicknessAttenuationDistance;
    vec4 attenuationColor;
    uvec4 textureLayers;
    uvec4 materialFlags;
};
layout(std430, set = 0, binding = 11) readonly buffer RtInstanceMetadataBuffer
{
    RtInstanceMetadata values[];
} rtInstances;
layout(std430, set = 0, binding = 12) readonly buffer RtPrimitiveMetadataBuffer
{
    RtPrimitiveMetadata values[];
} rtPrimitives;
layout(std430, set = 0, binding = 13) readonly buffer RtMaterialBuffer
{
    RtMaterialGpu values[];
} rtMaterials;
layout(std430, set = 0, binding = 14) readonly buffer RtStaticVertexBuffer
{
    StaticRtVertex values[];
} rtStaticVertices;
layout(std430, set = 0, binding = 15) readonly buffer RtStaticIndexBuffer
{
    uint values[];
} rtStaticIndices;
layout(set = 0, binding = 16) uniform sampler2DArray rtBaseColorTextures;
layout(set = 0, binding = 17) uniform sampler2DArray rtNormalTextures;
layout(set = 0, binding = 18) uniform sampler2DArray rtOrmTextures;
layout(set = 0, binding = 19) uniform sampler2DArray rtEmissiveTextures;
