// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: 9295d677a88c47b52321b1d749207b2024edf617dd2486074f1bad7903100332
const uint kRtInstanceMetadataCapacity = 20u;
const uint kRtStaticAssetCapacity = 8u;
const uint kRtPrimitiveMetadataCapacity = 32u;
const uint kRtMaterialCapacity = 32u;
const uint kRtTextureLayerCapacity = 16u;
const uint kRtFireEmitterCapacity = 4u;
const uint kRtActiveFireEmitterCapacity = 2u;

const uint kRtInstanceFlagStaticPbr = 1u;
const uint kRtInstanceFlagEmissive = 2u;
const uint kRtInstanceFlagTransmissive = 4u;
const uint kRtMaterialFlagDoubleSided = 1u;
const uint kRtMaterialFlagAlpha = 2u;
const uint kRtMaterialFlagTransmission = 4u;
const uint kRtMaterialFlagBaseColorTexture = 8u;
const uint kRtMaterialFlagNormalTexture = 16u;
const uint kRtMaterialFlagOrmTexture = 32u;
const uint kRtMaterialFlagEmissiveTexture = 64u;
const uint kRtMaterialFlagHeadPrimaryMasked = 128u;
const uint kRtMaterialFlagNearFacePrimaryMasked = 256u;
const uint kRtMaterialFlagThinWall = 512u;
const uint kRtMaterialFlagCertifiedClosedVolume = 1024u;

struct StaticRtVertex
{
    vec4 position;
    vec4 normal;
    vec4 tangent;
    vec4 uv0;
};
struct RtInstanceMetadata
{
    uint primitiveBase;
    uint primitiveCount;
    uint stableObjectId;
    uint flags;
    uint emitterIndex;
    uint assetIndex;
    uint reserved0;
    uint reserved1;
};
struct RtPrimitiveMetadata
{
    uint vertexOffset;
    uint indexOffset;
    uint indexCount;
    uint materialIndex;
};
struct RtDielectricDiagnostics
{
    uint transportOverflowCount;
    uint shadowOverflowCount;
    uint secondaryDielectricRejectCount;
    uint unclosedVolumeCount;
    uint primaryUnclosedVolumeCount;
    uint shadowUnclosedVolumeCount;
    uint productionPaneStackFailureCount;
    uint productionPaneSecondaryOriginCount;
    uint productionPaneSecondaryTerminalCount;
    uint productionPaneSecondarySameMediumCount;
    uint productionPaneSecondaryDifferentMediumCount;
    uint secondaryNearSelfHitCount;
    uint primaryOpenMissCount;
    uint primaryOpenOpaqueCount;
    uint primaryMismatchedExitCount;
    uint primaryInterfaceBudgetCount;
    uint primaryVolumeBudgetCount;
    uint shadowOpenMissCount;
    uint shadowMismatchedExitCount;
    uint primaryTirCount;
    uint primaryInterfaceBudgetOpenVolumeCount;
    uint primaryInterfaceBudgetClosedVolumeCount;
    uint shadowMismatchEmptyCount;
    uint shadowImplicitOriginExitCount;
    uint secondaryDielectricTerminalCount;
    uint primaryTirTerminationCount;
    uint shadowFiniteEndpointVolumeCount;
    uint primaryOpenOpaqueSameInstanceDifferentMaterialCount;
    uint primaryOpenOpaqueAfterTirCount;
    uint primaryOpenOpaqueTerminalInstanceMask;
    uint primaryOpenOpaqueVolumeInstanceMask;
    uint primaryOpenOpaqueTerminalMaterialMask;
    uint primaryClosedVolumeAbsorptionCount;
    uint primaryCertifiedClosedVolumeRecoveryCount;
    uint shadowCertifiedClosedVolumeRecoveryCount;
    uint certifiedClosedVolumeRecoveryReasonMask;
    uint primaryTorchPixelCount;
    uint primarySwordPixelCount;
    uint primaryPlayerPixelCount;
    uint primaryRewardRingPixelCount;
    uint primaryRewardBodyPixelCount;
};
struct RtMaterialGpu
{
    vec4 baseColorFactor;
    vec4 emissiveFactorStrength;
    vec4 metallicRoughnessOcclusionTransmission;
    vec4 iorThicknessAttenuationDistance;
    vec4 attenuationColor;
    uvec4 textureLayers;
    uvec4 materialFlags;
};
struct RtHeldLightGpu
{
    vec4 positionStrength;
};
struct RtFireEmitterGpu
{
    vec4 worldFromLocal0;
    vec4 worldFromLocal1;
    vec4 worldFromLocal2;
    vec4 worldFromLocal3;
    vec4 lightPositionStrength;
    vec4 colourIntensity;
    vec4 shape;
    vec4 animation;
    vec4 smokeEmbers;
    uvec4 identity;
};
layout(std430, set = 0, binding = 11) readonly buffer RtInstanceMetadataBuffer
{
    RtInstanceMetadata values[];
} rtInstances;
layout(std430, set = 0, binding = 12) readonly buffer RtPrimitiveMetadataBuffer
{
    RtPrimitiveMetadata values[];
} rtPrimitives;
layout(std430, set = 0, binding = 13) readonly buffer RtMaterialBuffer
{
    RtMaterialGpu values[];
} rtMaterials;
layout(std430, set = 0, binding = 14) readonly buffer RtStaticVertexBuffer
{
    StaticRtVertex values[];
} rtStaticVertices;
layout(std430, set = 0, binding = 15) readonly buffer RtStaticIndexBuffer
{
    uint values[];
} rtStaticIndices;
layout(set = 0, binding = 16) uniform sampler2DArray rtBaseColorTextures;
layout(set = 0, binding = 17) uniform sampler2DArray rtNormalTextures;
layout(set = 0, binding = 18) uniform sampler2DArray rtOrmTextures;
layout(set = 0, binding = 19) uniform sampler2DArray rtEmissiveTextures;
layout(std430, set = 0, binding = 20) readonly buffer RtHeldLightBuffer
{
    RtHeldLightGpu value;
} rtHeldLight;
layout(std430, set = 0, binding = 21) readonly buffer RtFireEmitterBuffer
{
    RtFireEmitterGpu values[4];
} rtFireEmitters;
layout(std430, set = 0, binding = 22) restrict buffer RtDielectricDiagnosticsBuffer
{
    RtDielectricDiagnostics value;
} rtDielectricDiagnostics;
