"""Authored note-level arrangements. This is a score builder, never an audio renderer."""
import json,copy,pathlib,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
SOURCE=ROOT/'source-reference/What_the_Dark_Keeps_Pocket_Chordsmith.json'
base=json.loads(SOURCE.read_text())
brief=json.load(open(ROOT/'manifests/composition-brief.json'))
# Each phrase below is explicitly composed: sixteenth offset : MIDI pitch : held sixteenths.
# Phrase rests, register, chord paths and counterlines differ by place and dramatic purpose.
def phrase(s):
 return [tuple(map(int,x.split(':'))) for x in s.split()] if s else []
def p(s):return phrase(s)
M=p('0:62:3 8:63:2 12:69:4 20:64:3 28:62:3 36:65:4 42:64:2 48:64:4 58:62:4')
COMPANION=p('2:67:3 8:69:3 14:71:2 20:69:4 28:67:3 36:66:4 44:64:3 52:62:6')
HOME=p('0:62:4 8:66:3 14:69:2 20:71:4 28:69:3 34:67:3 40:66:4 48:64:3 54:62:6')
# B=core identity; C=contrasting continuation; E=location-specific feature or boss escalation;
# H=story answer; D is explicitly authored threat/exposure, never generated by transposition.
SPECS=[
 dict(n=2,key='D',scale='minor',bpm=60,chord='felt_piano',ctype='sus2',lead='soft',second='soft_pluck',third='bell',oct=-2,
 harm=[[0,0,5,4],[0,3,5,0],[0,5,3,4],[0,0,6,4]],
 B='0:50:5 12:51:3 24:57:4 42:52:5 58:50:3',
 C='4:65:4 16:64:4 28:62:6 44:58:4 54:57:5',
 D='0:50:3 6:50:2 12:51:2 20:57:3 28:56:2 34:52:3 42:50:3 50:53:3 58:52:3',
 E='8:57:3 24:58:4 40:53:4 56:52:5', H='0:50:4 16:53:4 32:57:5 52:52:7',
 counter='10:69:2 30:64:2 46:62:2',feature='buried_history',rhythm='still'),
 dict(n=3,key='D',scale='minor',bpm=96,chord='harp',ctype='sus4',lead='western_fiddle',second='soft_pluck',third='muted_trumpet',oct=-1,
 harm=[[0,0,5,4],[3,0,6,4],[0,5,3,4],[5,3,0,0]],
 B='0:62:3 6:62:2 10:63:2 14:69:3 22:64:3 30:62:2 36:65:3 44:64:3 52:62:4 60:57:2',
 C='2:57:3 8:62:3 16:65:4 24:67:2 30:65:2 36:62:3 44:60:3 52:57:6',
 D='0:69:4 8:74:3 14:72:2 20:69:4 28:65:3 36:67:3 44:64:4 56:62:6',
 E='0:62:2 4:63:2 8:69:3 14:64:2 18:62:3 24:65:2 28:64:2 32:67:3 38:65:2 42:62:2 48:64:3 54:63:2 58:62:4',
 H='4:62:5 18:63:3 28:69:4 44:64:4 56:62:5',counter='4:57:2 18:53:3 34:58:3 50:57:3',feature='lantern_claim',rhythm='measured',boss=True),
 dict(n=4,key='G',scale='major',bpm=72,chord='harp',ctype='triad',lead='cowboy_whistle',second='soft_pluck',third='western_fiddle',oct=-1,
 harm=[[0,4,5,3],[0,2,3,4],[5,3,0,4],[3,0,4,0]],
 B='2:67:3 8:69:3 14:71:2 20:69:4 28:67:3 36:66:4 44:64:3 52:62:6',
 C='0:71:4 10:74:3 18:72:3 26:71:4 36:69:3 42:67:3 50:64:4 58:67:4',
 D='0:62:3 8:63:2 14:69:4 24:67:3 34:66:3 42:64:3 52:62:5',
 E='6:74:4 20:75:3 32:81:4 48:76:5',
 H='0:67:5 12:71:3 20:74:5 32:76:4 42:74:3 50:71:3 58:69:4',
 counter='6:62:2 22:66:2 38:64:2 54:62:2',feature='lookout_vista',rhythm='breath'),
 dict(n=5,key='D',scale='minor',bpm=80,chord='harp',ctype='sus2',lead='soft_pluck',second='cowboy_whistle',third='bell',oct=-1,
 harm=[[0,5,3,4],[0,6,5,4],[3,5,0,4],[5,3,0,0]],
 B='0:62:2 6:69:2 12:62:3 20:63:2 26:69:3 34:65:3 42:64:3 50:62:3 58:57:3',
 C='0:65:3 8:67:2 14:69:2 20:70:3 28:69:3 36:67:2 42:65:3 50:64:3 58:62:3',
 D='0:62:2 4:62:2 10:63:2 16:69:3 24:68:2 30:64:2 36:67:3 44:65:2 52:64:2 58:62:3',
 E='4:62:6 20:65:5 36:69:6 54:64:6',
 H='0:69:3 12:70:3 24:65:4 40:67:4 54:62:5',
 counter='8:74:3 24:76:3 40:74:3 56:69:3',feature='shrine',rhythm='walking'),
 dict(n=6,key='G',scale='major',bpm=84,chord='harp',ctype='triad',lead='western_fiddle',second='soft_pluck',third='cowboy_whistle',oct=-1,
 harm=[[0,3,0,4],[5,3,0,4],[2,5,3,4],[3,4,0,0]],
 B='0:67:3 6:71:2 10:74:2 16:72:3 22:71:2 28:69:3 34:67:3 40:69:2 46:71:3 54:67:5',
 C='2:62:3 8:64:3 14:67:2 20:69:4 28:67:3 36:66:3 42:64:3 50:62:5 58:67:3',
 D='0:64:4 12:63:2 20:62:4 32:67:4 44:66:3 54:64:5',
 E='4:71:4 16:69:4 28:67:5 44:64:4 56:62:5',
 H='0:67:3 8:69:2 14:71:2 20:74:4 30:72:2 36:71:3 44:69:3 52:67:7',
 counter='4:62:2 18:64:2 34:62:2 50:66:2',feature='hearth',rhythm='lilt'),
 dict(n=7,key='A',scale='minor',bpm=60,chord='felt_piano',ctype='sus2',lead='bell',second='soft',third='soft_pluck',oct=-1,
 harm=[[3,0,5,4],[0,6,3,0],[3,5,0,4],[5,3,0,0]],
 B='0:62:3 14:63:2 28:69:4 46:64:4 58:62:4',
 C='8:69:4 24:67:4 36:64:5 52:60:6',
 D='0:57:4 10:58:3 20:62:4 30:63:3 40:64:4 54:57:6',
 E='4:76:3 20:74:3 36:69:4 52:72:4',
 H='0:62:4 16:65:4 32:64:4 48:62:6',
 counter='10:57:5 32:60:5 54:57:4',feature='reflector_practice',rhythm='still'),
 dict(n=8,key='A',scale='minor',bpm=108,chord='felt_piano',ctype='sus4',lead='western_fiddle',second='bell',third='soft',oct=-1,
 harm=[[3,3,0,4],[0,5,3,4],[3,5,0,4],[3,0,3,3]],
 B='0:62:4 10:63:2 16:69:3 24:64:4 34:62:3 42:57:3 50:60:3 58:62:4',
 C='0:57:3 8:60:3 18:62:4 28:64:3 36:62:4 46:60:3 54:57:6',
 D='0:74:4 8:76:3 16:77:4 28:76:3 36:74:4 46:72:3 54:69:6',
 E='0:62:2 4:63:2 10:69:2 16:64:3 24:62:2 28:65:2 34:67:3 42:65:2 48:64:3 56:62:4',
 H='0:69:4 12:74:4 24:76:4 40:74:5 54:69:6',
 counter='6:69:2 22:74:2 38:72:2 54:69:2',feature='seal_release',rhythm='procession',boss=True),
 dict(n=9,key='D',scale='minor',bpm=88,chord='harp',ctype='triad',lead='soft_pluck',second='mellow_vibes',third='soft',oct=-1,
 harm=[[0,0,5,4],[0,6,3,4],[5,3,0,4],[0,5,0,0]],
 B='0:62:2 6:62:2 14:63:2 22:69:2 28:64:3 36:62:2 42:65:2 50:64:3 58:62:3',
 C='2:57:2 8:62:2 16:60:3 26:65:2 32:67:3 42:65:2 48:64:3 58:57:3',
 D='0:62:2 6:63:2 12:62:2 18:69:2 26:68:2 32:64:2 40:65:2 46:64:2 54:62:3 60:57:2',
 E='0:69:6 20:70:5 40:69:6 56:64:5',
 H='4:62:4 18:65:4 30:69:4 46:67:3 56:64:5',
 counter='10:50:3 26:57:3 44:53:3 60:52:2',feature='stand_lesson',rhythm='work'),
 dict(n=10,key='E',scale='minor',bpm=116,chord='harp',ctype='sus2',lead='soft_pluck',second='western_fiddle',third='muted_trumpet',oct=-1,
 harm=[[0,0,5,4],[3,0,6,4],[0,5,3,4],[5,3,0,0]],
 B='0:62:2 4:63:2 10:69:2 16:64:2 22:62:2 28:62:2 34:65:2 40:64:2 48:62:3 58:64:3',
 C='0:64:3 8:67:2 14:66:2 22:64:3 30:62:2 36:59:3 46:62:2 54:64:5',
 D='0:71:4 8:74:3 16:76:4 28:74:3 36:71:4 46:69:3 56:67:5',
 E='0:64:2 4:62:2 8:63:2 14:69:2 20:68:2 26:64:2 32:67:3 40:66:2 46:64:2 52:63:2 58:62:4',
 H='0:64:4 12:67:3 24:71:4 40:69:4 54:64:6',
 counter='6:52:2 22:59:2 38:55:3 54:54:2',feature='archive_release',rhythm='work',boss=True),
 dict(n=11,key='D',scale='minor',bpm=68,chord='harp',ctype='triad',lead='soft_pluck',second='cowboy_whistle',third='bell',oct=-1,
 harm=[[0,2,5,4],[3,5,0,4],[5,3,2,4],[0,3,5,0]],
 B='0:74:3 8:75:2 14:81:4 24:76:3 34:74:4 44:77:3 52:76:3 60:74:3',
 C='2:77:3 10:76:3 18:74:4 28:72:3 36:70:4 46:69:3 54:65:5',
 D='0:74:3 8:73:2 16:69:3 26:70:3 34:67:4 44:65:3 54:64:5',
 E='0:69:5 16:74:4 32:72:5 50:70:5',
 H='4:74:4 16:77:4 28:81:4 42:79:3 52:76:6',
 counter='6:62:3 22:65:4 38:69:3 54:64:4',feature='aperture_records',rhythm='breath'),
 dict(n=12,key='D',scale='minor',bpm=100,chord='felt_piano',ctype='sus2',lead='western_fiddle',second='soft_pluck',third='soft',oct=-1,
 harm=[[0,3,5,4],[5,3,0,4],[0,6,3,4],[3,5,0,0]],
 B='0:62:4 8:63:2 14:69:4 24:64:3 32:62:4 42:65:3 50:64:3 58:62:4',
 C='0:69:3 8:67:3 16:65:4 26:64:3 34:62:4 44:60:3 54:57:5',
 D='0:74:4 10:72:3 20:69:4 32:67:3 40:65:4 50:64:3 58:62:4',
 E='0:62:2 6:63:2 12:69:3 20:64:3 28:62:3 36:67:3 44:65:3 52:64:3 60:62:2',
 H='4:62:5 18:63:3 30:69:4 46:64:5',
 counter='6:57:3 22:62:3 38:58:3 54:57:3',feature='revelation_not_death',rhythm='measured',boss=True),
 dict(n=13,key='D',scale='minor',bpm=64,chord='harp',ctype='triad',lead='cowboy_whistle',second='soft_pluck',third='mellow_vibes',oct=-1,
 harm=[[5,2,3,0],[5,3,0,4],[0,5,3,4],[0,6,5,4]],
 B='0:62:4 10:63:2 16:69:5 28:64:4 40:62:4 50:65:4 60:64:3',
 C='2:70:4 14:69:3 24:65:5 38:67:4 50:64:5',
 D='0:62:3 8:63:3 20:69:4 34:68:4 46:64:4 58:63:3',
 E='4:69:6 24:70:5 44:69:6',
 H='0:74:4 12:76:4 24:78:4 38:81:5 52:78:6',
 counter='6:74:3 22:77:3 38:76:3 54:74:3',feature='ritual_preparation',rhythm='breath'),
 dict(n=14,key='D',scale='minor',bpm=120,chord='felt_piano',ctype='sus4',lead='western_fiddle',second='soft_pluck',third='muted_trumpet',oct=-1,
 harm=[[0,5,3,4],[0,6,5,4],[3,5,0,4],[5,3,0,0]],
 B='0:62:2 4:63:2 10:69:3 18:64:2 24:62:3 32:65:2 38:64:2 44:67:3 52:64:2 58:62:4',
 C='0:74:3 8:75:2 14:81:3 22:76:3 30:74:3 38:77:2 44:76:3 52:75:2 58:74:4',
 D='0:67:3 6:69:3 12:71:3 20:69:4 28:67:3 36:66:3 42:64:3 50:62:6',
 E='0:62:2 4:63:2 8:69:2 14:64:2 20:62:2 26:65:2 32:67:3 40:69:3 48:70:2 54:69:2 60:62:2',
 H='0:62:5 12:66:4 24:69:5 40:71:4 52:69:6',
 counter='6:50:3 22:58:3 38:55:3 54:57:3',feature='human_answer',rhythm='measured',boss=True),
 dict(n=15,key='D',scale='major',bpm=76,chord='harp',ctype='triad',lead='cowboy_whistle',second='soft_pluck',third='western_fiddle',oct=-1,
 harm=[[0,3,0,4],[5,3,0,4],[3,4,0,5],[3,4,0,0]],
 B='0:62:4 8:66:3 14:69:2 20:71:4 28:69:3 34:67:3 40:66:4 48:64:3 54:62:6',
 C='0:67:3 8:69:3 14:71:2 22:74:4 32:73:3 40:71:3 48:69:4 58:66:4',
 D='0:62:4 10:63:2 18:69:4 30:64:4 42:62:4 54:66:6',
 E='0:69:4 8:74:4 20:76:3 28:78:4 40:78:3 50:81:5',
 H='0:67:4 12:69:4 24:66:5 40:64:4 52:62:9',
 counter='6:57:3 22:62:3 38:57:3 54:62:3',feature='settled_home',rhythm='lilt')]

# Meanings are bank-specific; these override generic defaults to avoid false narrative event claims.
NAMES={
 2:['threshold','buried_corridors','waterfall_chamber','guard_threat','buried_history','danger_recedes','safe_aftermath','quiet_recovery'],
 3:['recognition','guarded_vigil','reposition','opening','late_pressure','regroup','confirmed_defeat','lantern_claim'],
 4:['rope_ascent','reunion','moonlit_trail','trail_threat','uncanny_waystone','reversible_return','lookout_arrival','lookout_vista'],
 5:['outbound_junction','road','road_continuation','road_threat','shrine','destination_bridge','completed_return','regional_approach'],
 6:['village_arrival','streets','hearth','concerned_return','churchyard_records','departure','return_welcome','communal_answer'],
 7:['lake_vista','dry_abbey','interior_continuation','duty_hall_threat','reflector_practice','short_crossing','post_seal_reflection','cleared_return'],
 8:['guardian_entrance','armoured','reflected_light_setup','actual_exposure','late_pressure','armour_recovers','confirmed_defeat','seal_release'],
 9:['gorge_vista','mint_work','archive_passage','smoke_pressure','stand_lesson','access_bridge','cleared_archive','return'],
10:['shell_entrance','shell_protected','mechanism_maintained','actual_exposure','late_pressure','shell_recovers','confirmed_defeat','seal_archive'],
11:['ridge_reveal','winter_garden','mirrored_gallery','keeper_approach','aperture_records','gallery_bridge','return','royal_records'],
12:['recognition_dialogue','wards_intact','receiver_selection','protection_broken','pressure','regroup','confirmed_defeat','revelation'],
13:['treasury_vista','genuine_riches','riches_continuation','ritual_suspicion','ritual_preparation','interrupt_safe_hold','release_bridge','soldiers_released'],
14:['rupture','confrontation','escalation','human_answer','culmination','phase_bridge','confirmed_defeat','release'],
15:['return_road_entry','playable_return','changed_home','memory_of_dark','credits_expansion','epilogue_bridge','final_cadence','settled_home']}

def new_track(events,octave,total=64):
 notes=[None]*total;hold=[False]*total
 offset=72+12*octave
 for st,midi,dur in events:
  assert 0<=midi-offset<=23,(st,midi,octave)
  notes[st]=midi-offset
  for x in range(st+1,min(st+dur,total)):
   hold[x]=True
 return notes,hold

def choose_oct(events):
 lo=min(x[1] for x in events) if events else 60
 hi=max(x[1] for x in events) if events else 72
 oct=(lo//12)-6
 assert hi-(72+12*oct)<=23,(lo,hi)
 return oct

def make_section(proj,s,spec,lead,harm,bars=4,role='loop'):
 total=64;active=bars*16
 lead=[e for e in lead if e[0]<active]
 # Supporting parts are truly intermittent; no held whole-section third melody voice.
 cp=p(spec['counter'])
 if s in 'AFG':cp=cp[:2]
 if s=='E':cp=[(i+2,m+12 if m<60 else m,d) for i,m,d in cp if i+2<active]
 if s=='C':cp=[(i+2,m+(2 if spec['scale']=='major' and m%12 in [2,7] else 0),d) for i,m,d in cp if i+2<active]
 cp=[e for e in cp if e[0]<active]
 # Tiny cadence/bell/horn responses, rather than a sustained sax drone.
 thirds=[]
 if s in 'BDH':
  thirds=[(12,lead[0][1]+(12 if spec['third']=='bell' else 0),2)] if lead else []
  if s=='H':thirds.append((44,lead[-1][1],3))
 if spec.get('boss') and s=='E':thirds=[(0,50 if spec['key']=='D' else 52,3),(32,57 if spec['key']=='D' else 59,3)]
 tracks=[];holds=[];octaves=[]
 for events in [lead,cp,thirds]:
  octv=choose_oct(events);notes,hold=new_track(events,octv); tracks.append(notes);holds.append(hold);octaves.append(octv)
 proj['progression'+s]=harm
 proj['sectionBars'][s]=bars
 proj['melodyTracks'+s]=tracks
 proj['melodyInstruments'+s]=[spec['lead'],spec['second'],spec['third']]
 proj['melodyOctaves'+s]=octaves
 for field,val in [('Mute',False),('Solo',False)]:proj['melody'+field+s]=[val]*3
 proj['melodyPan'+s]=[-0.10,0.22,-0.24]
 proj['melodyHold'+s]=holds
 for field in ['Slide','Tuplets']:proj['melody'+field+s]=[[False]*total for _ in range(3)]
 grid={x:[0]*total for x in ['kick','snare','hat','bass']}
 basshold=[False]*total
 for bar in range(bars):
  st=bar*16; grid['bass'][st]=1
  for pos in range(st+1,st+5):basshold[pos]=True
  if s in 'BD' and spec['rhythm'] in ['walking','lilt','work','procession','measured']:
   grid['bass'][st+8]=1
   for pos in range(st+9,st+11):basshold[pos]=True
  # No snare backbeat, hi-hat timekeeping or synthetic arpeggiator. Kick is a dry drum approximation.
  if s in 'BD' and spec['rhythm'] in ['walking','lilt','work','procession','measured']:
   grid['kick'][st]=1
   if spec['rhythm']=='work':grid['kick'][st+10]=1
   elif spec.get('boss') and bar%2==1:grid['kick'][st+8]=1
  if s=='E' and spec.get('boss'):
   grid['kick'][st]=2
   grid['kick'][st+10 if spec['rhythm']=='work' else st+8]=1
  if s=='D' and not spec.get('boss'):grid['kick'][st]=1
 if s in 'AFGH':
  # Cadences and bridges leave dialogue/transition space.
  grid['kick']=[0]*total
 for lane in grid:
  proj.setdefault('gridTuplets'+s,{})[lane]=[False]*total
 proj['grid'+s]=grid
 proj['bassHold'+s]=basshold
 proj['bassSlide'+s]=[False]*total
 proj['bassNotes'+s]=[None]*total
 proj['bassAccent'+s]=[False]*total
 proj['guitarPattern'+s]=['off']*total

manifest={'title':'The Horde — 15 adaptive score families','status':'Composition and synthesized review package. No game integration or production mastering claim.',
 'engine_revision':'0c6975cadcd4aba0047ab94170a2adabc722517f','source_theme_sha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
 'provenance':'Existing What the Dark Keeps score supplied from the private Horde repository. New companion scores and arrangements authored by OpenAI assistant for the user; existing author attribution is retained in the source package, not reassigned. No paid generation or third-party recordings.',
 'audio_status':'Actual Pocket Audio Core deterministic reference renders; not verified exact v68 live instrument parity. Instrument IDs are engine synthesis, not acoustic recordings.',
 'integration_status':'Future state-to-section proposal only. Current native eight-cue game and accepted original source are untouched.',
 'runtime_gaps':['True section-end scheduling is needed: current Core section quantization means bar.','Stinger events need an actual playback consumer.','thenReturnTo metadata needs a functioning return scheduler.','Layer control, dialogue ducking, saved state, pause/resume and native registration require integration and device tests.'],
 'families':[]}
# Main theme remains exactly its accepted compact musical content, including G/H F# and A/D drone fix.
main=copy.deepcopy(base);main['title']='01 What the Dark Keeps'
main['compositionProvenance']={'role':'Preserved source theme; schema migration only','sourceSha256':manifest['source_theme_sha256']}
(ROOT/'scores/01-what-the-dark-keeps.raw.json').write_text(json.dumps(main,indent=2)+'\n')
manifest['families'].append({'number':1,'title':'What the Dark Keeps','score':'01-what-the-dark-keeps.json','bpm':80,'key':'D','scale':'minor with intentional chromatic melody and F# release','original_preserved':True,'sections':{s:{'bars':base['sectionBars'][s],'name':x,'behavior':'one_shot' if s in 'CG' else 'loop'} for s,x in zip('ABCDEFGH',['original_title_statement','original_fuller_statement','original_transition','original_tomb_stillness','original_pressure','original_recovery','original_release','original_home_answer'])},'state_sequences':{'quiet_title':['A','A','D','A'],'full_title':['A','B','A','B'],'home_answer':['G','H','H']},'review_sequence':base['songSequence'],'notes':['A/D retained short third-part A4 is not a held drone.','G/H F# colour is intentional.','This file is not an overwrite of the current game asset.']})
for spec in SPECS:
 n=spec['n'];cue=brief['cues'][n-1];proj=copy.deepcopy(base)
 proj.update(title=f"{n:02d} {cue['title']}",projectVersion=16,key=spec['key'],scale=spec['scale'],bpm=spec['bpm'],chordType=spec['ctype'],chordInstrument=spec['chord'],masterVolume=.70,chordVolume=.19 if not spec.get('boss') else .21,beatVolume=.25 if not spec.get('boss') else .36,leadVolume=.46,swing=0,fxDelay=0,fxChorus=0,fxFlanger=0,fxReverb=.24,fxMix=.12,chordPlayMode='block',chordRhythmMode='sustain',chordOctave=-1 if n in [2,3,8,10,12,14] else 0,melodyPitchMode='chromatic',bassOn=True,sidechainOn=False,humanizeOn=False)
 proj['sectionBars']={}
 leads={s:p(spec[s]) for s in ['B','C','D','E','H']}
 # Entry is an invitation, not a maximal arrangement: begin in a lower density register.
 leads['A']=[(0,leads['B'][0][1],4),(16,leads['B'][min(1,len(leads['B'])-1)][1],3),(36,leads['B'][min(2,len(leads['B'])-1)][1],5),(54,leads['B'][-1][1],5)]
 # Brief transition returns to a single shared fifth and never contains a surprise reward quote.
 tonic={'D':62,'E':64,'G':67,'A':69}[spec['key']]
 if n==2:tonic-=12
 leads['F']=[(0,tonic+7 if tonic<69 else tonic-5,4),(16,tonic,6)]
 if n in [3,8,10,14]:leads['G']=[(0,tonic+7 if tonic<=64 else tonic,4),(12,tonic+3 if spec['scale']=='minor' else tonic+4,4),(28,tonic+2,5),(48,tonic,10)]
 elif n==12:leads['G']=[(4,62,4),(20,63,3),(40,64,7)]
 elif n==13:leads['G']=[(0,62,4),(12,63,3),(28,69,4),(44,68,5),(58,64,4)]
 elif n==15:leads['G']=[(0,67,5),(16,69,5),(32,66,5),(44,64,4),(52,62,11)]
 else:leads['G']=[(0,tonic,4),(16,tonic+3 if spec['scale']=='minor' else tonic+4,4),(32,tonic+2,5),(52,tonic,9)]
 for s in 'ABCDEFGH':
  hidx={'A':0,'B':0,'C':1,'D':2,'E':2,'F':3,'G':3,'H':3}[s]
  make_section(proj,s,spec,leads[s],spec['harm'][hidx],2 if s=='F' else 4)
 if spec.get('boss'):
  seq=list('ABBCBFCDBECEFGHH')
  states={'entrance':['A'],'protected':['B','C','B','C'],'setup':['C','B','C','B'],'exposure':['D','D'],'escalation':['E','B','E','C'],'reset':['F'],'confirmed_defeat':['G'],'aftermath':['H','H']}
 else:
  seq=list('ABBCCBBCEEBCHHDDBCFGH')
  states={'entry':['A'],'exploration':['B','C','B','C'],'quiet_feature':['E','C','E','C'],'threat':['D','D','C','D'],'bridge':['F'],'exit':['G'],'narrative_colour':['H','C']}
 if n==15:
  seq=list('ABBCBCHHDECBCEHFGH')
  states={'entry':['A','C'],'return':['B','C','B','C','B','H','B','C'],'village':['H','B','H','B'],'credits':['B','C','D','E','C','B','E','H'],'final_cadence':['F','G','H']}
 if n==13:states={'awe':['A','B'],'riches':['B','C','B','C','B','H','C','B'],'ritual_preparation':['E','C','E','C'],'ritual_hold':['F','F'],'soldiers_release':['H'],'entity_release':['G']}
 if n==14:states={'rupture':['A'],'confrontation':['B','C','B','C'],'escalation':['C','E','C','E'],'human_answer':['D','B','D','C'],'culmination':['E','D','E','C'],'bridge':['F'],'confirmed_defeat':['G'],'release':['H','H']}
 if n==6:states={'arrival':['A'],'streets':['B','C','B','H','B','C','H','B'],'hearth':['C','H','C','H'],'churchyard':['E','C','E','C'],'concerned_return':['D','C','D','E'],'departure':['F'],'welcome':['G']}
 proj['songSequence']=seq
 proj['compositionProvenance']={'familyId':cue['id'],'sourceThemeSha256':manifest['source_theme_sha256'],'role':'New original companion score derived from thematic source','motifTreatment':cue['motif_transformation'],'renderer':'Pocket Audio Core reference; acoustic timbre approximations'}
 slug=cue['id'].split('_',2)[2].replace('_','-');fn=f'{n:02d}-{slug}'
 (ROOT/'scores'/f'{fn}.raw.json').write_text(json.dumps(proj,indent=2)+'\n')
 manifest['families'].append({'number':n,'id':cue['id'],'title':cue['title'],'score':fn+'.json','bpm':spec['bpm'],'key':spec['key'],'scale':spec['scale'],'meter':'4/4','chord_colour':spec['ctype'],'voices':{'chords':spec['chord'],'melody':[spec['lead'],spec['second'],spec['third']]},'motif_treatment':cue['motif_transformation'],'story_guardrails':cue['dynamic_states_and_canon'],'sections':{s:{'bars':proj['sectionBars'][s],'name':NAMES[n][i],'behavior':'one_shot' if s in 'AG' else 'bridge' if s=='F' else 'loop','duration_seconds':proj['sectionBars'][s]*240/spec['bpm']} for i,s in enumerate('ABCDEFGH')},'state_sequences':states,'review_sequence':seq,'trigger_status':'Proposed authored events; not implemented runtime dispatch','loop_note':'Each loopable block rendered with prior-cycle carryover by actual Core engine; listenable arrangement is one possible path, not a scripted gameplay timer.'})
(ROOT/'manifests/cue-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Wrote15 authored raw scores and state manifest')
