// Generated by tools/GenerateRtPipelineVariantCatalog.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariants.h"

#include <array>
#include <cstddef>
#include <string_view>

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT raygen bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

struct RtPipelineCatalogRecord {
    RtPipelineVariantKey key;
    std::string_view canonicalKey;
    std::string_view artifactPath;
    std::string_view spirvSha256;
    std::string_view includeSha256;
    std::size_t words;
    std::size_t atomicInstructions;
    bool hasDiagnosticsBinding;
};

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/shipping_mobile_opaque_fast.inc", "810b2aca3e2147679b064fc6ef46cc93017b3def8ace4a7714c0ece7c57fbb50", "c0edc750bc610937d57a792deb6b06853b60337be9f587e4df190b1ef8ced373", 125253, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/shipping_mobile_generic_dielectric.inc", "9a3452cfb2abc8349e4573835312d2a3679ae5364ce2b9906f55f39d7811e682", "f0464ddcbc22d6806e2de540dedb00bedc2e6e6889c4c7a73ca72ce445d20552", 55015, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "shipping_high_opaque_fast", "src/vulkan/raytracing/variants/shipping_high_opaque_fast.inc", "810b2aca3e2147679b064fc6ef46cc93017b3def8ace4a7714c0ece7c57fbb50", "bb63ba2af69629ee3b590f4463cb221152c2d80b72f41f61e93ecffef4670889", 125253, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/shipping_high_generic_dielectric.inc", "589d221a3d32fa1d236e93f03b2fbb1c06eb0bdb1cbdce11e0e8493943442ca5", "78e22cf01e69e24a29c72be9fe4f91fa9e6d29d231b4a0421111cc8ded12285f", 55015, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_mobile_opaque_fast.inc", "b562973addb78d5d9c24c8d27211695eb582d2f26336dff29603a6c2e04420d7", "b2c8e5696aede4327ece85f26822eec4e29109168ea877544a3f333c0dc436c4", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_mobile_generic_dielectric.inc", "2d20a64a3ddbbe737db9cdbf01733c0882e017f9792972bb0e3584839b148d10", "01ff6afe07222476605d0cbedfc3fb028ec658fecd5a66b13a69a454e2c1e996", 56960, 32, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_high_opaque_fast.inc", "b562973addb78d5d9c24c8d27211695eb582d2f26336dff29603a6c2e04420d7", "1956c1e5c9962e293d266c7d74b913c8831c8039c508e4a84de8d2615cf3dc2d", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_high_generic_dielectric.inc", "933ccc972d8fc43cc55977c8d392b3366ed7e8eda2cc9f61dc82f77c616c162f", "2e03fa4f9d8b1568b6ad43af276d2dad9da011e6b32d0f55eb35abab5ef4b224", 56960, 32, true}};
#else
#error "Unsupported exact RT raygen bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
