// Generated by tools/GenerateRtPipelineVariantCatalog.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariants.h"

#include <array>
#include <cstddef>
#include <string_view>

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT raygen bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

struct RtPipelineCatalogRecord {
    RtPipelineVariantKey key;
    std::string_view canonicalKey;
    std::string_view artifactPath;
    std::string_view spirvSha256;
    std::string_view includeSha256;
    std::size_t words;
    std::size_t atomicInstructions;
    bool hasDiagnosticsBinding;
};

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/shipping_mobile_opaque_fast.inc", "6cf3aab980b2e4956cda8ea513c5b394a3190d02d226f95f69ac5a70258bfe72", "29294a7c3dde0fae4e8e43e7614a3bb81b7ab8cd4769f3b95a0d7e02e5090e1f", 139002, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/shipping_mobile_generic_dielectric.inc", "f73ac05d604754a7f95894d1cdaf075aa8e40df8ae9c66c02cd43453ff7a9f1d", "71f6f3b60cf06fdf1920e2c621890cde72116de3ea0837589f8651add2688579", 66053, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "shipping_high_opaque_fast", "src/vulkan/raytracing/variants/shipping_high_opaque_fast.inc", "82444ca07cf2609db8ca2a58c4d3b1a91bfaa626a57eec0e12b98510f7d106c7", "03b060693caccc3ea0ae98ffce589be2a52e13bfc536187228699b1dedad662f", 139777, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/shipping_high_generic_dielectric.inc", "415c9a896a0a0bf30a7d8a40041279c7e1292341fff66dd3dfd3047f96687af8", "edd01b56053ea4f2946b4d6ad8cf63ea425d8c9d8dd0a7e549b7805a99080dd7", 66428, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_mobile_opaque_fast.inc", "47da0772aa0348092e9d1a4f3d7828d4e6081c03ca6ba099d507b4218ca1d936", "bd98c0c05e0ae36de79fac4be55cf609f87a887d181c3aa55a89c89327d302f3", 140061, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_mobile_generic_dielectric.inc", "eb54787024750bda6d31542bab1a232703ac624afaf9280568019d62c7477994", "d97d60c41ca73835c529ff8fc47dbad3eb632b458f68b163dba7c6cd5b1a5f5a", 68260, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_high_opaque_fast.inc", "32e75617a12ef0f0ece9c60dd1c855766e2893dc1ab9e6f10183161ccc4df5ab", "113cafbef57fb6e9e422a1d981b968dfc3142357a7794d42fd94c708427f99ae", 140836, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_high_generic_dielectric.inc", "138deae23231b6004da777379919b7d133377202230f68a80bd43c9b704cbffe", "864e66b8e26bd2df0ff4790202df1bc11f8a2d574a13dde6d3e861b585ff6211", 68635, 41, true}};
#else
#error "Unsupported exact RT raygen bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
