// Generated by tools/GenerateRtPipelineVariantCatalog.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariants.h"

#include <array>
#include <cstddef>
#include <string_view>

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT raygen bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

struct RtPipelineCatalogRecord {
    RtPipelineVariantKey key;
    std::string_view canonicalKey;
    std::string_view artifactPath;
    std::string_view spirvSha256;
    std::string_view includeSha256;
    std::size_t words;
    std::size_t atomicInstructions;
    bool hasDiagnosticsBinding;
};

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/shipping_mobile_opaque_fast.inc", "382fe9f76e37b0b4ca81a709cab1f676bcbd7c6400a25d0922c4f86b889ba522", "c868ffbe50b17527b8e03002afd0cc609bb8f984870b16704ef9eef89a82ff1a", 125253, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/shipping_mobile_generic_dielectric.inc", "9a8af13a4fdae06d7beb7e28dbe9b175301b83b1b128777c43c74d77fad0d835", "2ae2b52e1e0ca1ebbe2e064bc5c469094e9049197cdc2313833067187e2d9a33", 56553, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "shipping_high_opaque_fast", "src/vulkan/raytracing/variants/shipping_high_opaque_fast.inc", "382fe9f76e37b0b4ca81a709cab1f676bcbd7c6400a25d0922c4f86b889ba522", "80ed6367ab3b1bad809e0fd4568074f7019364b13feb6d8d60c102dddd1865f0", 125253, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/shipping_high_generic_dielectric.inc", "0cfba0f8ec83c5fee8ebb2dd25366224e9d0d8860f6b15086bec5a736c4850e5", "5b6dc6413b19b81378bcf2508deea2ba30213c06430ad31c5243158291a57b5c", 56553, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_mobile_opaque_fast.inc", "8f523334ea42bf14932e3eecb5d1447d5f0015a3f1185b5e3431d5aa9dffab55", "29a67f25419e1b85b039383e52edc33f0ab6dd09ff631e741cc682896e7ff0d2", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_mobile_generic_dielectric.inc", "095a0824bcb1bcaabf0281b04a74cca2d2ed9c597c0602b7ab7d2bae7b21de0b", "d7f9cc07ebd736ec59185837e92ce75a111dafc2af95ceddb49de507754325b2", 58760, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_high_opaque_fast.inc", "8f523334ea42bf14932e3eecb5d1447d5f0015a3f1185b5e3431d5aa9dffab55", "2c3b9d39ee080d53bdb20f38e492631b20ba835939f30355e9a2ad4c6ab16fa1", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_high_generic_dielectric.inc", "d0f1ae7a600187c8e0f85f3ef706c8eae52629406097d65f4c46e0caf40e41d7", "bc97db3b241abcb0cf491b59ce051ec48b55133d3439fc647e7f0755ce619c0f", 58760, 41, true}};
#else
#error "Unsupported exact RT raygen bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
