// Generated by tools/GenerateRayQueryComputeVariants.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariantCatalog.generated.h"

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT RayQuery compute bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_opaque_fast.inc", "5002afa7ac6ce0d03fc749742bb0832a1006b9f01bb1c6ab8490710790a79133", "ff22045916802572f8940711f2d7e0c28bcec1b6ca9b92e3bf10fbcca49ef303", 125318, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_generic_dielectric.inc", "c2bd389812841161951f819e0f12e95c929aa3f49ec87d9849393a687d20ebde", "f1e5dd2affd921db51d25b9b4c627dd2bcdbd76b9b712e357f9ca2652f6a4936", 61022, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_opaque_fast.inc", "5002afa7ac6ce0d03fc749742bb0832a1006b9f01bb1c6ab8490710790a79133", "8823b3c4183d3e8f2bcf391dce3fead0b52cf719bbc1fa75b7f2703500df2b9b", 125318, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_generic_dielectric.inc", "f0e10d5af6017aa9b27e0538cd90375da215f366aac1bb35e02ba60468e94c60", "366c498c0fb4eb8d72ce9acf48438f08ed73e4fb352427629205965862acc87a", 61022, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_opaque_fast.inc", "5787949c6d51da50ace6cde4f98cdc82f54816aae83639646c57b0ce294a6c50", "81d6af5b1a9474a0a1de10a2c19a7cf103a9c37dd02e439e842113e6940d2a9d", 140467, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_generic_dielectric.inc", "410dc6f69a7a425115403a64873ac2d827f2ad9144e77568561ed35cba296727", "cec4e9e0b47011a0f3a0f36d30f87ceade2607997107c62fe6a9b1f0dd822c08", 67310, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_opaque_fast.inc", "c1e4622ae5df0c87a06c36d803617c7d4e0227845cd33a9dd38de5f0d956ff58", "6e05eef7df381b4f1017f20864dd5f5fc1f3b94e628180c160369001b1ce92bb", 126377, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_generic_dielectric.inc", "a88abd1880da54d159e0e912cc9030a51a46cb5759bf29bc548c99b08c62cbd8", "92a588b53864e79795bb0f21bef8229173a4c4a072e8b03e03ebfa0eb505bd69", 63229, 41, true}};
#else
#error "Unsupported exact RT RayQuery compute bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
