// Generated by tools/GenerateRayQueryComputeVariants.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariantCatalog.generated.h"

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT RayQuery compute bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_opaque_fast.inc", "d05eec30c1fbdc256a34856c1a87f8f5789137ea79d04027bcaa059259565e64", "208e167ca225f1bea67de5b9027b87cbe0392ee6f1c4d1ae894f49ea4d83b2e2", 147347, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_generic_dielectric.inc", "72b03e6bce4b3800a686a106290647af078a119c5da38c7d4cce870477df86d0", "3a3b1a5acf5f5a648ab6408c4441ad70c51e47df0d1793868ba322744e3caebc", 71470, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_opaque_fast.inc", "f21fb2fe7acf6991d43ba697cc40ca05460e844b0be5c6e5d1e0bd5dcc193ee5", "d25a8ad722e135556be93989e95dd1bdef334a5716152b009cc212d7bb959752", 148122, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_generic_dielectric.inc", "cf819ead8266e755bc3c783380f983a7a0d3e0e338834234cb643f78a65ef1bb", "e1a95df1ccdefb9837f21c04a4807313420e8b0bbd1042cf97a1c51816b36b09", 71845, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_opaque_fast.inc", "a48b9bb85102c62a1695d62b98ed4cdd4075d2343b1366e79e9e42e7f26aa945", "0ddf68ff02bb69b7d9d8ac77879e3edac9a3ad9ab80d736392105a0b6da9c81d", 148406, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_generic_dielectric.inc", "c26dd2ce36c68f02ef22df49e3f08a7612f80a0a84d8cd696a474af667f85451", "f1cd40011bd654749079a75bda137a0080ba0b595895d3a2503662507257e7d0", 73677, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_opaque_fast.inc", "6728cadff8b1dc2bc7d18d370b1bf6ccff1533908efd587a77e3848b7b940f95", "22ef0140ab45886463295b030b93fa97cc7344507b4f2403355f6a1d6d34d607", 149181, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_generic_dielectric.inc", "5f51a1b5175b29db3b5fb34eaa784fe3322607059b190fa770cd7835e3cef760", "42757b207612aef464ba3c750b604a76836a40cf8cee77946fcc7855083edf94", 74052, 41, true}};
#else
#error "Unsupported exact RT RayQuery compute bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
