// Generated by tools/GenerateRayQueryComputeVariants.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariantCatalog.generated.h"

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT RayQuery compute bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_opaque_fast.inc", "5002afa7ac6ce0d03fc749742bb0832a1006b9f01bb1c6ab8490710790a79133", "07d31a4ac20ae288399d4bb4544cc7f4ba63b2bd67eb8239c057ce592da34436", 125318, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_generic_dielectric.inc", "c2bd389812841161951f819e0f12e95c929aa3f49ec87d9849393a687d20ebde", "58fe2c8692abc509e623d4035c76792e007d5bd83e4f6ef72ce61a60e2b4bd82", 61022, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_opaque_fast.inc", "5002afa7ac6ce0d03fc749742bb0832a1006b9f01bb1c6ab8490710790a79133", "13a8c043ac5ef39e0c300b40ff13000fea940fff0622d6f487b068e5c78b318b", 125318, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_generic_dielectric.inc", "f0e10d5af6017aa9b27e0538cd90375da215f366aac1bb35e02ba60468e94c60", "3b13df5557f0ebeb09d6de9ca5f0b05d59915760f332c81ceb25e60984666ef9", 61022, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_opaque_fast.inc", "c1e4622ae5df0c87a06c36d803617c7d4e0227845cd33a9dd38de5f0d956ff58", "c3f3570ef2caf9941e5a86d0d0d7fff83d425e8f20afbed0abf116a570cc5286", 126377, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_generic_dielectric.inc", "e18171591d4b07ccc3e7fb071400a6581e1fc132aec06dd37c09f88c7792e302", "eb412a64169e334fd0c17e7efcca7210f51b72cb74d311d57d2d4850ceb336f9", 63229, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_opaque_fast.inc", "c1e4622ae5df0c87a06c36d803617c7d4e0227845cd33a9dd38de5f0d956ff58", "0ad07dfcc3bbf63204942cd93166b6b7b809dba8b94cbdd0966122cfd7428a7b", 126377, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_generic_dielectric.inc", "a88abd1880da54d159e0e912cc9030a51a46cb5759bf29bc548c99b08c62cbd8", "dc4ac8654d2c831c44e714c54508da7ce3a6270a1841728caec7efea8dc8f293", 63229, 41, true}};
#else
#error "Unsupported exact RT RayQuery compute bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
