// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: 8b4e86226b2d0bfda4e93b6a97eb80986764734c3cec1815e5d9d4270bdf36fa
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace horde::vulkan::raytracing
{

inline constexpr char kRtSceneAbiDefinitionSha256[] = "8b4e86226b2d0bfda4e93b6a97eb80986764734c3cec1815e5d9d4270bdf36fa";
inline constexpr std::uint32_t kRtInstanceMetadataCapacity = 20u;
inline constexpr std::uint32_t kRtStaticAssetCapacity = 8u;
inline constexpr std::uint32_t kRtPrimitiveMetadataCapacity = 32u;
inline constexpr std::uint32_t kRtMaterialCapacity = 32u;
inline constexpr std::uint32_t kRtTextureLayerCapacity = 16u;

inline constexpr std::uint32_t kRtBindingInstanceMetadata = 11u;
inline constexpr std::uint32_t kRtBindingPrimitiveMetadata = 12u;
inline constexpr std::uint32_t kRtBindingMaterials = 13u;
inline constexpr std::uint32_t kRtBindingStaticVertices = 14u;
inline constexpr std::uint32_t kRtBindingStaticIndices = 15u;
inline constexpr std::uint32_t kRtBindingBaseColorTextures = 16u;
inline constexpr std::uint32_t kRtBindingNormalTextures = 17u;
inline constexpr std::uint32_t kRtBindingOrmTextures = 18u;
inline constexpr std::uint32_t kRtBindingEmissiveTextures = 19u;

enum class RtInstanceFlag : std::uint32_t
{
    StaticPbr = 1u,
    Emissive = 2u,
    Transmissive = 4u,
};

enum class RtMaterialFlag : std::uint32_t
{
    DoubleSided = 1u,
    Alpha = 2u,
    Transmission = 4u,
    BaseColorTexture = 8u,
    NormalTexture = 16u,
    OrmTexture = 32u,
    EmissiveTexture = 64u,
};

struct alignas(16) RtInstanceMetadata
{
    std::uint32_t primitiveBase = 0u;
    std::uint32_t primitiveCount = 0u;
    std::uint32_t stableObjectId = 0u;
    std::uint32_t flags = 0u;
    std::uint32_t emitterIndex = 0u;
    std::uint32_t assetIndex = 0u;
    std::uint32_t reserved0 = 0u;
    std::uint32_t reserved1 = 0u;
};
static_assert(sizeof(RtInstanceMetadata) == 32u);

struct alignas(16) RtPrimitiveMetadata
{
    std::uint32_t vertexOffset = 0u;
    std::uint32_t indexOffset = 0u;
    std::uint32_t indexCount = 0u;
    std::uint32_t materialIndex = 0u;
};
static_assert(sizeof(RtPrimitiveMetadata) == 16u);

struct alignas(16) RtMaterialGpu
{
    std::array<float, 4u> baseColorFactor{};
    std::array<float, 4u> emissiveFactorStrength{};
    std::array<float, 4u> metallicRoughnessOcclusionTransmission{};
    std::array<float, 4u> iorThicknessAttenuationDistance{};
    std::array<float, 4u> attenuationColor{};
    std::array<std::uint32_t, 4u> textureLayers{};
    std::array<std::uint32_t, 4u> materialFlags{};
};
static_assert(sizeof(RtMaterialGpu) == 112u);
static_assert(alignof(RtMaterialGpu) == 16u);

} // namespace horde::vulkan::raytracing
