// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: 4321458556798c07f213965b12948d87ea311a4b57d2dda84ef6494bfce0be50
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace horde::vulkan::raytracing
{

inline constexpr char kRtSceneAbiDefinitionSha256[] = "4321458556798c07f213965b12948d87ea311a4b57d2dda84ef6494bfce0be50";
inline constexpr std::uint32_t kRtInstanceMetadataCapacity = 20u;
inline constexpr std::uint32_t kRtStaticAssetCapacity = 8u;
inline constexpr std::uint32_t kRtPrimitiveMetadataCapacity = 32u;
inline constexpr std::uint32_t kRtMaterialCapacity = 32u;
inline constexpr std::uint32_t kRtTextureLayerCapacity = 16u;
inline constexpr std::uint32_t kRtFireEmitterCapacity = 4u;
inline constexpr std::uint32_t kRtActiveFireEmitterCapacity = 2u;

inline constexpr std::uint32_t kRtBindingInstanceMetadata = 11u;
inline constexpr std::uint32_t kRtBindingPrimitiveMetadata = 12u;
inline constexpr std::uint32_t kRtBindingMaterials = 13u;
inline constexpr std::uint32_t kRtBindingStaticVertices = 14u;
inline constexpr std::uint32_t kRtBindingStaticIndices = 15u;
inline constexpr std::uint32_t kRtBindingBaseColorTextures = 16u;
inline constexpr std::uint32_t kRtBindingNormalTextures = 17u;
inline constexpr std::uint32_t kRtBindingOrmTextures = 18u;
inline constexpr std::uint32_t kRtBindingEmissiveTextures = 19u;
inline constexpr std::uint32_t kRtBindingHeldLight = 20u;
inline constexpr std::uint32_t kRtBindingFireEmitters = 21u;

enum class RtInstanceFlag : std::uint32_t
{
    StaticPbr = 1u,
    Emissive = 2u,
    Transmissive = 4u,
};

enum class RtMaterialFlag : std::uint32_t
{
    DoubleSided = 1u,
    Alpha = 2u,
    Transmission = 4u,
    BaseColorTexture = 8u,
    NormalTexture = 16u,
    OrmTexture = 32u,
    EmissiveTexture = 64u,
    HeadPrimaryMasked = 128u,
    NearFacePrimaryMasked = 256u,
    ThinWall = 512u,
};

struct alignas(16) StaticRtVertex
{
    std::array<float, 4u> position{};
    std::array<float, 4u> normal{};
    std::array<float, 4u> tangent{};
    std::array<float, 4u> uv0{};
};
static_assert(sizeof(StaticRtVertex) == 64u);
static_assert(alignof(StaticRtVertex) == 16u);
static_assert(offsetof(StaticRtVertex, position) == 0u);
static_assert(offsetof(StaticRtVertex, normal) == 16u);
static_assert(offsetof(StaticRtVertex, tangent) == 32u);
static_assert(offsetof(StaticRtVertex, uv0) == 48u);
struct alignas(16) RtInstanceMetadata
{
    std::uint32_t primitiveBase = 0u;
    std::uint32_t primitiveCount = 0u;
    std::uint32_t stableObjectId = 0u;
    std::uint32_t flags = 0u;
    std::uint32_t emitterIndex = 0u;
    std::uint32_t assetIndex = 0u;
    std::uint32_t reserved0 = 0u;
    std::uint32_t reserved1 = 0u;
};
static_assert(sizeof(RtInstanceMetadata) == 32u);
static_assert(alignof(RtInstanceMetadata) == 16u);
static_assert(offsetof(RtInstanceMetadata, primitiveBase) == 0u);
static_assert(offsetof(RtInstanceMetadata, primitiveCount) == 4u);
static_assert(offsetof(RtInstanceMetadata, stableObjectId) == 8u);
static_assert(offsetof(RtInstanceMetadata, flags) == 12u);
static_assert(offsetof(RtInstanceMetadata, emitterIndex) == 16u);
static_assert(offsetof(RtInstanceMetadata, assetIndex) == 20u);
static_assert(offsetof(RtInstanceMetadata, reserved0) == 24u);
static_assert(offsetof(RtInstanceMetadata, reserved1) == 28u);
struct alignas(16) RtPrimitiveMetadata
{
    std::uint32_t vertexOffset = 0u;
    std::uint32_t indexOffset = 0u;
    std::uint32_t indexCount = 0u;
    std::uint32_t materialIndex = 0u;
};
static_assert(sizeof(RtPrimitiveMetadata) == 16u);
static_assert(alignof(RtPrimitiveMetadata) == 16u);
static_assert(offsetof(RtPrimitiveMetadata, vertexOffset) == 0u);
static_assert(offsetof(RtPrimitiveMetadata, indexOffset) == 4u);
static_assert(offsetof(RtPrimitiveMetadata, indexCount) == 8u);
static_assert(offsetof(RtPrimitiveMetadata, materialIndex) == 12u);
struct alignas(16) RtMaterialGpu
{
    std::array<float, 4u> baseColorFactor{};
    std::array<float, 4u> emissiveFactorStrength{};
    std::array<float, 4u> metallicRoughnessOcclusionTransmission{};
    std::array<float, 4u> iorThicknessAttenuationDistance{};
    std::array<float, 4u> attenuationColor{};
    std::array<std::uint32_t, 4u> textureLayers{};
    std::array<std::uint32_t, 4u> materialFlags{};
};
static_assert(sizeof(RtMaterialGpu) == 112u);
static_assert(alignof(RtMaterialGpu) == 16u);
static_assert(offsetof(RtMaterialGpu, baseColorFactor) == 0u);
static_assert(offsetof(RtMaterialGpu, emissiveFactorStrength) == 16u);
static_assert(offsetof(RtMaterialGpu, metallicRoughnessOcclusionTransmission) == 32u);
static_assert(offsetof(RtMaterialGpu, iorThicknessAttenuationDistance) == 48u);
static_assert(offsetof(RtMaterialGpu, attenuationColor) == 64u);
static_assert(offsetof(RtMaterialGpu, textureLayers) == 80u);
static_assert(offsetof(RtMaterialGpu, materialFlags) == 96u);
struct alignas(16) RtHeldLightGpu
{
    std::array<float, 4u> positionStrength{};
};
static_assert(sizeof(RtHeldLightGpu) == 16u);
static_assert(alignof(RtHeldLightGpu) == 16u);
static_assert(offsetof(RtHeldLightGpu, positionStrength) == 0u);
struct alignas(16) RtFireEmitterGpu
{
    std::array<float, 4u> worldFromLocal0{};
    std::array<float, 4u> worldFromLocal1{};
    std::array<float, 4u> worldFromLocal2{};
    std::array<float, 4u> worldFromLocal3{};
    std::array<float, 4u> lightPositionStrength{};
    std::array<float, 4u> colourIntensity{};
    std::array<float, 4u> shape{};
    std::array<float, 4u> animation{};
    std::array<float, 4u> smokeEmbers{};
    std::array<std::uint32_t, 4u> identity{};
};
static_assert(sizeof(RtFireEmitterGpu) == 160u);
static_assert(alignof(RtFireEmitterGpu) == 16u);
static_assert(offsetof(RtFireEmitterGpu, worldFromLocal0) == 0u);
static_assert(offsetof(RtFireEmitterGpu, worldFromLocal1) == 16u);
static_assert(offsetof(RtFireEmitterGpu, worldFromLocal2) == 32u);
static_assert(offsetof(RtFireEmitterGpu, worldFromLocal3) == 48u);
static_assert(offsetof(RtFireEmitterGpu, lightPositionStrength) == 64u);
static_assert(offsetof(RtFireEmitterGpu, colourIntensity) == 80u);
static_assert(offsetof(RtFireEmitterGpu, shape) == 96u);
static_assert(offsetof(RtFireEmitterGpu, animation) == 112u);
static_assert(offsetof(RtFireEmitterGpu, smokeEmbers) == 128u);
static_assert(offsetof(RtFireEmitterGpu, identity) == 144u);
} // namespace horde::vulkan::raytracing
