import json,struct,pathlib,hashlib,numpy as np
from collections import Counter
R=pathlib.Path(__file__).resolve().parents[1];reports=[]
for p in sorted((R/'models').glob('*.glb')):
 b=p.read_bytes();magic,ver,total=struct.unpack_from('<III',b);ln,ty=struct.unpack_from('<II',b,12);d=json.loads(b[20:20+ln]);bin_offset=20+ln+8
 def arr(i):
  a=d['accessors'][i];v=d['bufferViews'][a['bufferView']];dt={5126:np.float32,5123:np.uint16,5125:np.uint32}[a['componentType']];n={'VEC3':3,'VEC2':2,'SCALAR':1,'VEC4':4}[a['type']];return np.frombuffer(b,dtype=dt,count=a['count']*n,offset=bin_offset+v.get('byteOffset',0)+a.get('byteOffset',0)).reshape(-1,n)
 prim=d['meshes'][0]['primitives'][0];pos=arr(prim['attributes']['POSITION']);ind=arr(prim['indices']).reshape(-1,3);uv=arr(prim['attributes']['TEXCOORD_0']);norm=arr(prim['attributes']['NORMAL']);ar=np.linalg.norm(np.cross(pos[ind[:,1]]-pos[ind[:,0]],pos[ind[:,2]]-pos[ind[:,0]]),axis=1)*.5
 _,weld=np.unique(np.round(pos,5),axis=0,return_inverse=True);wf=weld[ind];edges=Counter(tuple(sorted((int(f[i]),int(f[(i+1)%3])))) for f in wf for i in range(3));rep={'file':p.name,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'magic_valid':magic==0x46546c67,'version':ver,'length_valid':total==len(b),'triangles':len(ind),'vertices':len(pos),'finite_positions_normals_uv':bool(np.isfinite(pos).all() and np.isfinite(norm).all() and np.isfinite(uv).all()),'indices_valid':bool(ind.max()<len(pos)),'degenerate_triangles_area_lt_1e_12':int(sum(ar<1e-12)),'bounds_min':pos.min(0).tolist(),'bounds_max':pos.max(0).tolist(),'welded_boundary_edges':sum(v==1 for v in edges.values()),'welded_nonmanifold_edges':sum(v>2 for v in edges.values()),'materials':d.get('materials'),'images':d.get('images'),'external_dependencies':[v.get('uri') for group in ('buffers','images') for v in d.get(group,[]) if 'uri'in v],'extensionsRequired':d.get('extensionsRequired',[]),'meshes':len(d['meshes'])};reports.append(rep)
(R/'evidence/glb_static_inspection.json').write_text(json.dumps(reports,indent=2)+'\n');print(json.dumps([{k:r[k] for k in ('file','triangles','degenerate_triangles_area_lt_1e_12','welded_boundary_edges','welded_nonmanifold_edges')} for r in reports],indent=2))
