[CmdletBinding()]
param(
    [string]$DefinitionPath = "",
    [string]$CpuOutputPath = "",
    [string]$GlslOutputPath = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($DefinitionPath)) {
    $DefinitionPath = Join-Path $repoRoot "src\vulkan\raytracing\RtSceneAbi.def"
}
if ([string]::IsNullOrWhiteSpace($CpuOutputPath)) {
    $CpuOutputPath = Join-Path $repoRoot "src\vulkan\raytracing\RtSceneAbi.generated.h"
}
if ([string]::IsNullOrWhiteSpace($GlslOutputPath)) {
    $GlslOutputPath = Join-Path $repoRoot "shaders\raytracing\include\rt_scene_abi.generated.glsl"
}

$definition = Get-Content -LiteralPath $DefinitionPath -Raw | ConvertFrom-Json
if ($definition.schema -ne 1) { throw "RT scene ABI definition schema must be 1." }
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $DefinitionPath).Hash.ToLowerInvariant()
$c = $definition.capacities
$b = $definition.bindings
$i = $definition.instanceFlags
$m = $definition.materialFlags

$cpu = @"
// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: $hash
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace horde::vulkan::raytracing
{

inline constexpr char kRtSceneAbiDefinitionSha256[] = "$hash";
inline constexpr std::uint32_t kRtInstanceMetadataCapacity = $($c.instanceMetadata)u;
inline constexpr std::uint32_t kRtStaticAssetCapacity = $($c.staticAssets)u;
inline constexpr std::uint32_t kRtPrimitiveMetadataCapacity = $($c.primitives)u;
inline constexpr std::uint32_t kRtMaterialCapacity = $($c.materials)u;
inline constexpr std::uint32_t kRtTextureLayerCapacity = $($c.textureLayers)u;

inline constexpr std::uint32_t kRtBindingInstanceMetadata = $($b.instanceMetadata)u;
inline constexpr std::uint32_t kRtBindingPrimitiveMetadata = $($b.primitiveMetadata)u;
inline constexpr std::uint32_t kRtBindingMaterials = $($b.materials)u;
inline constexpr std::uint32_t kRtBindingStaticVertices = $($b.staticVertices)u;
inline constexpr std::uint32_t kRtBindingStaticIndices = $($b.staticIndices)u;
inline constexpr std::uint32_t kRtBindingBaseColorTextures = $($b.baseColorTextures)u;
inline constexpr std::uint32_t kRtBindingNormalTextures = $($b.normalTextures)u;
inline constexpr std::uint32_t kRtBindingOrmTextures = $($b.ormTextures)u;
inline constexpr std::uint32_t kRtBindingEmissiveTextures = $($b.emissiveTextures)u;

enum class RtInstanceFlag : std::uint32_t
{
    StaticPbr = $($i.staticPbr)u,
    Emissive = $($i.emissive)u,
    Transmissive = $($i.transmissive)u,
};

enum class RtMaterialFlag : std::uint32_t
{
    DoubleSided = $($m.doubleSided)u,
    Alpha = $($m.alpha)u,
    Transmission = $($m.transmission)u,
};

struct alignas(16) RtInstanceMetadata
{
    std::uint32_t primitiveBase = 0u;
    std::uint32_t primitiveCount = 0u;
    std::uint32_t stableObjectId = 0u;
    std::uint32_t flags = 0u;
    std::uint32_t emitterIndex = 0u;
    std::uint32_t assetIndex = 0u;
    std::uint32_t reserved0 = 0u;
    std::uint32_t reserved1 = 0u;
};
static_assert(sizeof(RtInstanceMetadata) == 32u);

struct alignas(16) RtPrimitiveMetadata
{
    std::uint32_t vertexOffset = 0u;
    std::uint32_t indexOffset = 0u;
    std::uint32_t indexCount = 0u;
    std::uint32_t materialIndex = 0u;
};
static_assert(sizeof(RtPrimitiveMetadata) == 16u);

struct alignas(16) RtMaterialGpu
{
    std::array<float, 4u> baseColorFactor{};
    std::array<float, 4u> emissiveFactorStrength{};
    std::array<float, 4u> metallicRoughnessOcclusionTransmission{};
    std::array<float, 4u> iorThicknessAttenuationDistance{};
    std::array<float, 4u> attenuationColor{};
    std::array<std::uint32_t, 4u> textureLayers{};
    std::array<std::uint32_t, 4u> materialFlags{};
};
static_assert(sizeof(RtMaterialGpu) == 112u);
static_assert(alignof(RtMaterialGpu) == 16u);

} // namespace horde::vulkan::raytracing
"@

$glsl = @"
// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: $hash
const uint kRtInstanceMetadataCapacity = $($c.instanceMetadata)u;
const uint kRtStaticAssetCapacity = $($c.staticAssets)u;
const uint kRtPrimitiveMetadataCapacity = $($c.primitives)u;
const uint kRtMaterialCapacity = $($c.materials)u;
const uint kRtTextureLayerCapacity = $($c.textureLayers)u;

const uint kRtInstanceFlagStaticPbr = $($i.staticPbr)u;
const uint kRtInstanceFlagEmissive = $($i.emissive)u;
const uint kRtInstanceFlagTransmissive = $($i.transmissive)u;
const uint kRtMaterialFlagDoubleSided = $($m.doubleSided)u;
const uint kRtMaterialFlagAlpha = $($m.alpha)u;
const uint kRtMaterialFlagTransmission = $($m.transmission)u;

struct RtInstanceMetadata
{
    uvec4 geometry;
    uvec4 routing;
};
layout(std430, set = 0, binding = $($b.instanceMetadata)) readonly buffer RtInstanceMetadataBuffer
{
    RtInstanceMetadata values[];
} rtInstances;

struct RtPrimitiveMetadata
{
    uvec4 geometry;
};
layout(std430, set = 0, binding = $($b.primitiveMetadata)) readonly buffer RtPrimitiveMetadataBuffer
{
    RtPrimitiveMetadata values[];
} rtPrimitives;

struct RtMaterialGpu
{
    vec4 baseColorFactor;
    vec4 emissiveFactorStrength;
    vec4 metallicRoughnessOcclusionTransmission;
    vec4 iorThicknessAttenuationDistance;
    vec4 attenuationColor;
    uvec4 textureLayers;
    uvec4 materialFlags;
};
layout(std430, set = 0, binding = $($b.materials)) readonly buffer RtMaterialBuffer
{
    RtMaterialGpu values[];
} rtMaterials;

struct StaticRtVertex
{
    vec4 position;
    vec4 normal;
    vec4 tangent;
    vec4 uv0;
};
layout(std430, set = 0, binding = $($b.staticVertices)) readonly buffer RtStaticVertexBuffer
{
    StaticRtVertex values[];
} rtStaticVertices;
layout(std430, set = 0, binding = $($b.staticIndices)) readonly buffer RtStaticIndexBuffer
{
    uint values[];
} rtStaticIndices;
layout(set = 0, binding = $($b.baseColorTextures)) uniform sampler2DArray rtBaseColorTextures;
layout(set = 0, binding = $($b.normalTextures)) uniform sampler2DArray rtNormalTextures;
layout(set = 0, binding = $($b.ormTextures)) uniform sampler2DArray rtOrmTextures;
layout(set = 0, binding = $($b.emissiveTextures)) uniform sampler2DArray rtEmissiveTextures;
"@

function Normalize-Newlines([string]$text) {
    return $text.Replace("`r`n", "`n").TrimEnd("`r", "`n") + "`n"
}

function Publish-OrCheck([string]$path, [string]$content) {
    $normalized = Normalize-Newlines $content
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "RT scene ABI generated output is missing: $path"
        }
        $existing = Normalize-Newlines (Get-Content -LiteralPath $path -Raw)
        if ($existing -cne $normalized) {
            throw "RT scene ABI generated output is stale: $path"
        }
        return
    }
    $directory = Split-Path -Parent $path
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
    [System.IO.File]::WriteAllText($path, $normalized, [System.Text.UTF8Encoding]::new($false))
}

Publish-OrCheck $CpuOutputPath $cpu
Publish-OrCheck $GlslOutputPath $glsl
if ($Check) {
    Write-Output "RT scene ABI generated outputs are current ($hash)."
} else {
    Write-Output "Generated RT scene ABI CPU/GLSL outputs ($hash)."
}
