[CmdletBinding()]
param(
    [string]$DefinitionPath = "",
    [string]$CpuOutputPath = "",
    [string]$GlslOutputPath = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($DefinitionPath)) { $DefinitionPath = Join-Path $repoRoot "src\vulkan\raytracing\RtSceneAbi.def" }
if ([string]::IsNullOrWhiteSpace($CpuOutputPath)) { $CpuOutputPath = Join-Path $repoRoot "src\vulkan\raytracing\RtSceneAbi.generated.h" }
if ([string]::IsNullOrWhiteSpace($GlslOutputPath)) { $GlslOutputPath = Join-Path $repoRoot "shaders\raytracing\include\rt_scene_abi.generated.glsl" }

$definition = Get-Content -LiteralPath $DefinitionPath -Raw | ConvertFrom-Json
if ($definition.schema -ne 1) { throw "RT scene ABI definition schema must be 1." }
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $DefinitionPath).Hash.ToLowerInvariant()
$c = $definition.capacities
$b = $definition.bindings
$i = $definition.instanceFlags
$m = $definition.materialFlags
$records = @($definition.records)
if ($records.Count -eq 0) { throw "RT scene ABI definition must declare record layouts." }

$typeInfo = @{
    uint = [ordered]@{ Cpu = "std::uint32_t"; Glsl = "uint"; Size = 4; Alignment = 4; Initializer = " = 0u;" }
    float4 = [ordered]@{ Cpu = "std::array<float, 4u>"; Glsl = "vec4"; Size = 16; Alignment = 16; Initializer = "{};" }
    uint4 = [ordered]@{ Cpu = "std::array<std::uint32_t, 4u>"; Glsl = "uvec4"; Size = 16; Alignment = 16; Initializer = "{};" }
}
$requiredRecords = @("StaticRtVertex", "RtInstanceMetadata", "RtPrimitiveMetadata", "RtMaterialGpu")
foreach ($requiredRecord in $requiredRecords) {
    if (@($records | Where-Object name -eq $requiredRecord).Count -ne 1) {
        throw "RT scene ABI definition must declare exactly one '$requiredRecord' record."
    }
}

foreach ($record in $records) {
    if ([string]::IsNullOrWhiteSpace($record.name) -or [int]$record.alignment -lt 1) { throw "RT scene ABI contains an invalid record declaration." }
    $cursor = 0
    foreach ($field in @($record.fields)) {
        $info = $typeInfo[[string]$field.type]
        if ($null -eq $info) { throw "RT scene ABI field '$($record.name).$($field.name)' has unsupported type '$($field.type)'." }
        $expectedOffset = [int]([Math]::Ceiling($cursor / [double]$info.Alignment) * $info.Alignment)
        if ([int]$field.offset -ne $expectedOffset) {
            throw "RT scene ABI field '$($record.name).$($field.name)' declares offset $($field.offset), expected $expectedOffset."
        }
        $cursor = $expectedOffset + $info.Size
    }
    $computedSize = [int]([Math]::Ceiling($cursor / [double][int]$record.alignment) * [int]$record.alignment)
    if ([int]$record.size -ne $computedSize) {
        throw "RT scene ABI record '$($record.name)' declares size $($record.size) but its fields occupy $computedSize bytes."
    }
}

$cpuRecords = @($records | ForEach-Object {
    $record = $_
    $fieldLines = @($record.fields | ForEach-Object {
        $info = $typeInfo[[string]$_.type]
        "    $($info.Cpu) $($_.name)$($info.Initializer)"
    }) -join "`n"
    $offsetAssertions = @($record.fields | ForEach-Object {
        "static_assert(offsetof($($record.name), $($_.name)) == $($_.offset)u);"
    }) -join "`n"
@"
struct alignas($($record.alignment)) $($record.name)
{
$fieldLines
};
static_assert(sizeof($($record.name)) == $($record.size)u);
static_assert(alignof($($record.name)) == $($record.alignment)u);
$offsetAssertions
"@
}) -join "`n"

$glslRecords = @($records | ForEach-Object {
    $record = $_
    $fieldLines = @($record.fields | ForEach-Object {
        $info = $typeInfo[[string]$_.type]
        "    $($info.Glsl) $($_.name);"
    }) -join "`n"
@"
struct $($record.name)
{
$fieldLines
};
"@
}) -join "`n"

$cpu = @"
// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: $hash
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace horde::vulkan::raytracing
{

inline constexpr char kRtSceneAbiDefinitionSha256[] = "$hash";
inline constexpr std::uint32_t kRtInstanceMetadataCapacity = $($c.instanceMetadata)u;
inline constexpr std::uint32_t kRtStaticAssetCapacity = $($c.staticAssets)u;
inline constexpr std::uint32_t kRtPrimitiveMetadataCapacity = $($c.primitives)u;
inline constexpr std::uint32_t kRtMaterialCapacity = $($c.materials)u;
inline constexpr std::uint32_t kRtTextureLayerCapacity = $($c.textureLayers)u;
inline constexpr std::uint32_t kRtFireEmitterCapacity = $($c.fireEmitters)u;
inline constexpr std::uint32_t kRtActiveFireEmitterCapacity = $($c.activeFireEmitters)u;

inline constexpr std::uint32_t kRtBindingInstanceMetadata = $($b.instanceMetadata)u;
inline constexpr std::uint32_t kRtBindingPrimitiveMetadata = $($b.primitiveMetadata)u;
inline constexpr std::uint32_t kRtBindingMaterials = $($b.materials)u;
inline constexpr std::uint32_t kRtBindingStaticVertices = $($b.staticVertices)u;
inline constexpr std::uint32_t kRtBindingStaticIndices = $($b.staticIndices)u;
inline constexpr std::uint32_t kRtBindingBaseColorTextures = $($b.baseColorTextures)u;
inline constexpr std::uint32_t kRtBindingNormalTextures = $($b.normalTextures)u;
inline constexpr std::uint32_t kRtBindingOrmTextures = $($b.ormTextures)u;
inline constexpr std::uint32_t kRtBindingEmissiveTextures = $($b.emissiveTextures)u;
inline constexpr std::uint32_t kRtBindingHeldLight = $($b.heldLight)u;
inline constexpr std::uint32_t kRtBindingFireEmitters = $($b.fireEmitters)u;

enum class RtInstanceFlag : std::uint32_t
{
    StaticPbr = $($i.staticPbr)u,
    Emissive = $($i.emissive)u,
    Transmissive = $($i.transmissive)u,
};

enum class RtMaterialFlag : std::uint32_t
{
    DoubleSided = $($m.doubleSided)u,
    Alpha = $($m.alpha)u,
    Transmission = $($m.transmission)u,
    BaseColorTexture = $($m.baseColorTexture)u,
    NormalTexture = $($m.normalTexture)u,
    OrmTexture = $($m.ormTexture)u,
    EmissiveTexture = $($m.emissiveTexture)u,
    HeadPrimaryMasked = $($m.headPrimaryMasked)u,
    NearFacePrimaryMasked = $($m.nearFacePrimaryMasked)u,
};

$cpuRecords
} // namespace horde::vulkan::raytracing
"@

$glsl = @"
// Generated by tools/generate-rt-scene-abi.ps1 from RtSceneAbi.def.
// Definition SHA-256: $hash
const uint kRtInstanceMetadataCapacity = $($c.instanceMetadata)u;
const uint kRtStaticAssetCapacity = $($c.staticAssets)u;
const uint kRtPrimitiveMetadataCapacity = $($c.primitives)u;
const uint kRtMaterialCapacity = $($c.materials)u;
const uint kRtTextureLayerCapacity = $($c.textureLayers)u;
const uint kRtFireEmitterCapacity = $($c.fireEmitters)u;
const uint kRtActiveFireEmitterCapacity = $($c.activeFireEmitters)u;

const uint kRtInstanceFlagStaticPbr = $($i.staticPbr)u;
const uint kRtInstanceFlagEmissive = $($i.emissive)u;
const uint kRtInstanceFlagTransmissive = $($i.transmissive)u;
const uint kRtMaterialFlagDoubleSided = $($m.doubleSided)u;
const uint kRtMaterialFlagAlpha = $($m.alpha)u;
const uint kRtMaterialFlagTransmission = $($m.transmission)u;
const uint kRtMaterialFlagBaseColorTexture = $($m.baseColorTexture)u;
const uint kRtMaterialFlagNormalTexture = $($m.normalTexture)u;
const uint kRtMaterialFlagOrmTexture = $($m.ormTexture)u;
const uint kRtMaterialFlagEmissiveTexture = $($m.emissiveTexture)u;
const uint kRtMaterialFlagHeadPrimaryMasked = $($m.headPrimaryMasked)u;
const uint kRtMaterialFlagNearFacePrimaryMasked = $($m.nearFacePrimaryMasked)u;

$glslRecords
layout(std430, set = 0, binding = $($b.instanceMetadata)) readonly buffer RtInstanceMetadataBuffer
{
    RtInstanceMetadata values[];
} rtInstances;
layout(std430, set = 0, binding = $($b.primitiveMetadata)) readonly buffer RtPrimitiveMetadataBuffer
{
    RtPrimitiveMetadata values[];
} rtPrimitives;
layout(std430, set = 0, binding = $($b.materials)) readonly buffer RtMaterialBuffer
{
    RtMaterialGpu values[];
} rtMaterials;
layout(std430, set = 0, binding = $($b.staticVertices)) readonly buffer RtStaticVertexBuffer
{
    StaticRtVertex values[];
} rtStaticVertices;
layout(std430, set = 0, binding = $($b.staticIndices)) readonly buffer RtStaticIndexBuffer
{
    uint values[];
} rtStaticIndices;
layout(set = 0, binding = $($b.baseColorTextures)) uniform sampler2DArray rtBaseColorTextures;
layout(set = 0, binding = $($b.normalTextures)) uniform sampler2DArray rtNormalTextures;
layout(set = 0, binding = $($b.ormTextures)) uniform sampler2DArray rtOrmTextures;
layout(set = 0, binding = $($b.emissiveTextures)) uniform sampler2DArray rtEmissiveTextures;
layout(std430, set = 0, binding = $($b.heldLight)) readonly buffer RtHeldLightBuffer
{
    RtHeldLightGpu value;
} rtHeldLight;
layout(std430, set = 0, binding = $($b.fireEmitters)) readonly buffer RtFireEmitterBuffer
{
    RtFireEmitterGpu values[$($c.fireEmitters)];
} rtFireEmitters;
"@

function Normalize-Newlines([string]$text) { return $text.Replace("`r`n", "`n").TrimEnd("`r", "`n") + "`n" }
function Publish-OrCheck([string]$path, [string]$content) {
    $normalized = Normalize-Newlines $content
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path)) { throw "RT scene ABI generated output is missing: $path" }
        $existing = Normalize-Newlines (Get-Content -LiteralPath $path -Raw)
        if ($existing -cne $normalized) { throw "RT scene ABI generated output is stale: $path" }
        return
    }
    New-Item -ItemType Directory -Path (Split-Path -Parent $path) -Force | Out-Null
    [System.IO.File]::WriteAllText($path, $normalized, [System.Text.UTF8Encoding]::new($false))
}

Publish-OrCheck $CpuOutputPath $cpu
Publish-OrCheck $GlslOutputPath $glsl
if ($Check) { Write-Output "RT scene ABI generated outputs are current ($hash)." }
else { Write-Output "Generated RT scene ABI CPU/GLSL outputs ($hash)." }
