// Generated by tools/GenerateRtPipelineVariantCatalog.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariants.h"

#include <array>
#include <cstddef>
#include <string_view>

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT raygen bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

struct RtPipelineCatalogRecord {
    RtPipelineVariantKey key;
    std::string_view canonicalKey;
    std::string_view artifactPath;
    std::string_view spirvSha256;
    std::string_view includeSha256;
    std::size_t words;
    std::size_t atomicInstructions;
    bool hasDiagnosticsBinding;
};

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/shipping_mobile_opaque_fast.inc", "1e2b907a3b1fce730711aeb97f369440d4f8d0b0c5d1619290e1b35b61952f23", "e89f55a048b6063d6c318aabc36be14330965856c8a3f83adbfdf168565377b2", 118525, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/shipping_mobile_generic_dielectric.inc", "ec04234ca954a07070e669657b4bbfcf93fdb556a66be31580975c1a6df9e2ab", "73ce36f1dda2167152f65dcd031c5422d066dd2fef398525c9e696382e580d9c", 57093, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "shipping_high_opaque_fast", "src/vulkan/raytracing/variants/shipping_high_opaque_fast.inc", "66e39df9f53b058fb62cbfa913d424b161c93be4aff59a1685cf8b7e54bb9c4b", "6284c1cc86b1696e1c7915fa251e957bb914a051e0835847bc374ee1a00bc681", 125253, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/shipping_high_generic_dielectric.inc", "79e80a489e93f02f99292cf76bc8f7405645159b63d1fe2bcca407b65f16b8fa", "6ed84973208ec9b23ec4afbb24a596a406cd1357aa5a8832c460ab6d0e3705fa", 60963, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast}, "diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_mobile_opaque_fast.inc", "8dbebd86eeed23b388626719e6f9946b8027df754869b5811673e24036ae12c9", "f04bde76b605c2c2378787921f874fda743991296fb74a57fda5d54a4f411104", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric}, "diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_mobile_generic_dielectric.inc", "9865690c11de315c1c4e49af7d14eb8963b24dc522abfc01c53979bb1a5f5a91", "be1f9c8ccec96300bbeae4df9f8aa96db5804ce6c678039f3779fbfec6a3ddcb", 63170, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtPipelineCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast}, "diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/diagnostic_high_opaque_fast.inc", "8dbebd86eeed23b388626719e6f9946b8027df754869b5811673e24036ae12c9", "7da63772093d1af5238382120ea15758e8bba2d311187296de611f32f8c9cdc4", 126312, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric}, "diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/diagnostic_high_generic_dielectric.inc", "feac38eca1df17159bca4d490825b7e3750742b05bb07cd2f6db4eec42261b5c", "1311506d446672994f5e252acf128d6c78a36e3becc61a07c96a01a4a3887cbd", 63170, 41, true}};
#else
#error "Unsupported exact RT raygen bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
