// Generated by tools/GenerateRayQueryComputeVariants.ps1. Do not edit.
#pragma once

#include "vulkan/raytracing/RtPipelineVariantCatalog.generated.h"

#if !defined(HORDE_RT_SELECTED_INSTRUMENTATION) || !defined(HORDE_RT_SELECTED_DIELECTRIC_QUALITY)
#error "The RT RayQuery compute bundle policy must define both selected dimensions."
#endif

namespace horde::vulkan::raytracing::detail {

#if HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_opaque_fast.inc", "7b35d5961d27c3385ed97fed8d4f4a00ccc0884b257a2480bd9ef56741a4d295", "42b109102ca6ec2bfd9eb09074b24a5241f20aad7f1a148521085e1cc461c277", 118590, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_mobile_generic_dielectric.inc", "f72f6ee70cae2608e5b3f787cb37f3b51907e9078158deb70ada3273bbc97e76", "9ef32c2b18b8c480954facba3206043442d84577407c78c894ae971eecf5e454", 57156, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 0 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_opaque_fast.inc", "5002afa7ac6ce0d03fc749742bb0832a1006b9f01bb1c6ab8490710790a79133", "03a6a00e03fcefe67315ede0c216d4c86b5f9cf1552633df923e676b9ef89f5b", 125318, 0, false},
    RtPipelineCatalogRecord{{RtInstrumentation::Shipping, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_shipping_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_shipping_high_generic_dielectric.inc", "f0e10d5af6017aa9b27e0538cd90375da215f366aac1bb35e02ba60468e94c60", "d701c12d4616455f17a192ca1dd7a6fb7fe961be8ba51115a77681d592c3e786", 61022, 0, false}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 0
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_opaque_fast.inc", "c1e4622ae5df0c87a06c36d803617c7d4e0227845cd33a9dd38de5f0d956ff58", "4329f2b1db2a20ab9c0d794398c69215cdcd9b7b21aff47f8535f45dea91f43d", 126377, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::Mobile, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_mobile_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_mobile_generic_dielectric.inc", "e18171591d4b07ccc3e7fb071400a6581e1fc132aec06dd37c09f88c7792e302", "25bfd6269f489d1a48803e307e5491bc3f976f3217b924d462d0b7fa01a7fe5c", 63229, 41, true}};
#elif HORDE_RT_SELECTED_INSTRUMENTATION == 1 && HORDE_RT_SELECTED_DIELECTRIC_QUALITY == 1
inline constexpr std::array<RtPipelineCatalogRecord, 2> kSelectedRtRayQueryCatalog{
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::OpaqueFast, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_opaque_fast", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_opaque_fast.inc", "c1e4622ae5df0c87a06c36d803617c7d4e0227845cd33a9dd38de5f0d956ff58", "015ba09a68ac10b821bc617093b789baf36919317f23e65d618aceff0ae5ebc9", 126377, 5, true},
    RtPipelineCatalogRecord{{RtInstrumentation::Diagnostic, DielectricQuality::High, RtMaterialStrategy::GenericDielectric, RtExecutionBackend::RayQueryCompute}, "rayquery_compute_diagnostic_high_generic_dielectric", "src/vulkan/raytracing/variants/rayquery_compute_diagnostic_high_generic_dielectric.inc", "a88abd1880da54d159e0e912cc9030a51a46cb5759bf29bc548c99b08c62cbd8", "3a8dc888e306f0cf9f4ab03412983cc0b4fb2685be04856a92a93fc724835dc9", 63229, 41, true}};
#else
#error "Unsupported exact RT RayQuery compute bundle policy."
#endif

} // namespace horde::vulkan::raytracing::detail
