# Explicit developer/CI restore; no configure-time download or Runtime install.
function(horde_rt_add_report_webview2 repo_root)
    if(TARGET horde_rt_report_webview2)
        return()
    endif()
    if(NOT WIN32)
        message(FATAL_ERROR "The report verification WebView2 adapter is Windows-only")
    endif()
    set(HORDE_RT_WEBVIEW2_SDK_ROOT
        "${repo_root}/build/dependencies/Microsoft.Web.WebView2/1.0.4258.31"
        CACHE PATH "Explicitly restored pinned WebView2 SDK directory")
    file(SHA256 "${repo_root}/third_party/webview2-sdk/manifest.json" manifest_hash)
    if(NOT manifest_hash STREQUAL "0e4039382c34cf206401d44b6a8ec02fb9b43f42cf5834bd559cae0629c67b7e")
        message(FATAL_ERROR "Report WebView2 SDK manifest pin mismatch")
    endif()
    file(READ "${repo_root}/third_party/webview2-sdk/manifest.json" manifest)
    string(JSON package GET "${manifest}" package)
    string(JSON version GET "${manifest}" version)
    string(JSON file_count LENGTH "${manifest}" files)
    if(NOT package STREQUAL "Microsoft.Web.WebView2" OR
       NOT version STREQUAL "1.0.4258.31" OR NOT file_count EQUAL 6)
        message(FATAL_ERROR "Report WebView2 SDK identity/inventory mismatch")
    endif()
    foreach(index RANGE 0 5)
        string(JSON relative GET "${manifest}" files ${index} path)
        string(JSON expected_hash GET "${manifest}" files ${index} sha256)
        string(JSON expected_bytes GET "${manifest}" files ${index} bytes)
        set(path "${HORDE_RT_WEBVIEW2_SDK_ROOT}/${relative}")
        if(NOT EXISTS "${path}" OR IS_SYMLINK "${path}")
            message(FATAL_ERROR "Missing report WebView2 SDK; run tools/restore-report-webview2.ps1: ${relative}")
        endif()
        file(SIZE "${path}" actual_bytes)
        file(SHA256 "${path}" actual_hash)
        if(NOT actual_bytes EQUAL expected_bytes OR NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Report WebView2 SDK hash/size mismatch: ${relative}")
        endif()
    endforeach()
    if(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
        set(architecture arm64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(architecture x64)
    else()
        set(architecture x86)
    endif()
    add_library(horde_rt_report_webview2 STATIC IMPORTED GLOBAL)
    set_target_properties(horde_rt_report_webview2 PROPERTIES
        IMPORTED_LOCATION "${HORDE_RT_WEBVIEW2_SDK_ROOT}/build/native/${architecture}/WebView2LoaderStatic.lib"
        INTERFACE_INCLUDE_DIRECTORIES "${HORDE_RT_WEBVIEW2_SDK_ROOT}/build/native/include"
        INTERFACE_LINK_LIBRARIES "ole32;shlwapi;version;advapi32")
endfunction()
