# Shared release-identity reader. This file is deliberately usable before the
# root project() call and from Android's nested native CMake configure.
if(NOT DEFINED HORDE_RT_REPO_ROOT)
    get_filename_component(HORDE_RT_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(_horde_rt_version_file "${HORDE_RT_REPO_ROOT}/VERSION")
set(_horde_rt_version_code_map_file "${HORDE_RT_REPO_ROOT}/version-code-map.json")
if(NOT EXISTS "${_horde_rt_version_file}")
    message(FATAL_ERROR "Horde RT semantic version source is missing: ${_horde_rt_version_file}")
endif()
if(NOT EXISTS "${_horde_rt_version_code_map_file}")
    message(FATAL_ERROR "Horde RT Android version-code map is missing: ${_horde_rt_version_code_map_file}")
endif()

# This module is included by both the root configure and Android's nested
# native configure. Track the raw authorities here so an ordinary build from
# an existing tree regenerates resources and compile definitions after either
# source changes.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_horde_rt_version_file}"
    "${_horde_rt_version_code_map_file}")

file(READ "${_horde_rt_version_file}" _horde_rt_version_hex HEX)
if(_horde_rt_version_hex MATCHES "^efbbbf")
    message(FATAL_ERROR "VERSION must be valid UTF-8 without a byte-order mark: ${_horde_rt_version_file}")
endif()

file(STRINGS "${_horde_rt_version_file}" _horde_rt_version_lines ENCODING UTF-8)
list(LENGTH _horde_rt_version_lines _horde_rt_version_line_count)
if(NOT _horde_rt_version_line_count EQUAL 1)
    message(FATAL_ERROR "VERSION must contain exactly one MAJOR.MINOR.PATCH line without whitespace.")
endif()
list(GET _horde_rt_version_lines 0 HORDE_RT_PACKAGE_VERSION)
if(NOT HORDE_RT_PACKAGE_VERSION MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "VERSION is not a strict MAJOR.MINOR.PATCH semantic version: ${HORDE_RT_PACKAGE_VERSION}")
endif()
file(READ "${_horde_rt_version_file}" _horde_rt_version_raw)
string(LENGTH "${HORDE_RT_PACKAGE_VERSION}" _horde_rt_version_length)
string(LENGTH "${_horde_rt_version_raw}" _horde_rt_version_raw_length)
math(EXPR _horde_rt_version_lf_length "${_horde_rt_version_length} + 1")
math(EXPR _horde_rt_version_crlf_length "${_horde_rt_version_length} + 2")
if(_horde_rt_version_raw_length EQUAL _horde_rt_version_lf_length)
    string(SUBSTRING "${_horde_rt_version_raw}" ${_horde_rt_version_length} 1 _horde_rt_version_terminator)
    if(NOT _horde_rt_version_terminator STREQUAL "\n")
        message(FATAL_ERROR "VERSION may only have one final LF or CRLF line terminator.")
    endif()
elseif(_horde_rt_version_raw_length EQUAL _horde_rt_version_crlf_length)
    string(SUBSTRING "${_horde_rt_version_raw}" ${_horde_rt_version_length} 2 _horde_rt_version_terminator)
    if(NOT _horde_rt_version_terminator STREQUAL "\r\n")
        message(FATAL_ERROR "VERSION may only have one final LF or CRLF line terminator.")
    endif()
elseif(NOT _horde_rt_version_raw_length EQUAL _horde_rt_version_length)
    message(FATAL_ERROR "VERSION must contain exactly one MAJOR.MINOR.PATCH line without whitespace.")
endif()
set(HORDE_RT_DISPLAY_VERSION "${HORDE_RT_PACKAGE_VERSION}")
set(HORDE_RT_BUILD_ID "${HORDE_RT_PACKAGE_VERSION}")
set(HORDE_RT_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(HORDE_RT_VERSION_MINOR "${CMAKE_MATCH_2}")
set(HORDE_RT_VERSION_PATCH "${CMAKE_MATCH_3}")
set(HORDE_RT_WINDOWS_FILE_VERSION "${HORDE_RT_VERSION_MAJOR},${HORDE_RT_VERSION_MINOR},${HORDE_RT_VERSION_PATCH},0")
set(HORDE_RT_WINDOWS_ASSEMBLY_VERSION "${HORDE_RT_VERSION_MAJOR}.${HORDE_RT_VERSION_MINOR}.${HORDE_RT_VERSION_PATCH}.0")

file(READ "${_horde_rt_version_code_map_file}" _horde_rt_version_code_map_hex HEX)
if(_horde_rt_version_code_map_hex MATCHES "^efbbbf")
    message(FATAL_ERROR "Android version-code map must be valid UTF-8 without a byte-order mark: ${_horde_rt_version_code_map_file}")
endif()
file(READ "${_horde_rt_version_code_map_file}" _horde_rt_version_code_map)
string(JSON _horde_rt_map_type ERROR_VARIABLE _horde_rt_map_type_error TYPE "${_horde_rt_version_code_map}")
if(_horde_rt_map_type_error)
    message(FATAL_ERROR "Android version-code map is not valid UTF-8 JSON: ${_horde_rt_version_code_map_file}")
endif()
if(NOT _horde_rt_map_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Android version-code map must be a JSON object.")
endif()
string(JSON _horde_rt_android_codes_type ERROR_VARIABLE _horde_rt_android_codes_type_error TYPE
    "${_horde_rt_version_code_map}" androidVersionCodes)
if(_horde_rt_android_codes_type_error)
    message(FATAL_ERROR "Android version-code map has no androidVersionCodes object.")
endif()
if(NOT _horde_rt_android_codes_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Android version-code map androidVersionCodes must be an object.")
endif()
string(REGEX MATCHALL "\\\"${HORDE_RT_PACKAGE_VERSION}\\\"[ \t\r\n]*:" _horde_rt_active_map_assignments
    "${_horde_rt_version_code_map}")
list(LENGTH _horde_rt_active_map_assignments _horde_rt_active_map_assignment_count)
if(NOT _horde_rt_active_map_assignment_count EQUAL 1)
    message(FATAL_ERROR "Android version-code map must contain exactly one active assignment for ${HORDE_RT_PACKAGE_VERSION}.")
endif()
string(JSON _horde_rt_map_value_type ERROR_VARIABLE _horde_rt_map_value_type_error TYPE
    "${_horde_rt_version_code_map}" androidVersionCodes "${HORDE_RT_PACKAGE_VERSION}")
if(_horde_rt_map_value_type_error)
    message(FATAL_ERROR "Android version-code map has no active assignment for ${HORDE_RT_PACKAGE_VERSION}.")
endif()
string(JSON HORDE_RT_ANDROID_VERSION_CODE ERROR_VARIABLE _horde_rt_map_error GET
    "${_horde_rt_version_code_map}" androidVersionCodes "${HORDE_RT_PACKAGE_VERSION}")
if(NOT _horde_rt_map_value_type STREQUAL "NUMBER" OR _horde_rt_map_error OR
   NOT HORDE_RT_ANDROID_VERSION_CODE MATCHES "^[1-9][0-9]*$" OR
   HORDE_RT_ANDROID_VERSION_CODE GREATER 2147483647)
    message(FATAL_ERROR "Android version-code map has no positive integer for ${HORDE_RT_PACKAGE_VERSION}.")
endif()

unset(_horde_rt_version_file)
unset(_horde_rt_version_code_map_file)
unset(_horde_rt_version_hex)
unset(_horde_rt_version_lines)
unset(_horde_rt_version_line_count)
unset(_horde_rt_version_raw)
unset(_horde_rt_version_length)
unset(_horde_rt_version_raw_length)
unset(_horde_rt_version_lf_length)
unset(_horde_rt_version_crlf_length)
unset(_horde_rt_version_terminator)
unset(_horde_rt_version_code_map)
unset(_horde_rt_version_code_map_hex)
unset(_horde_rt_map_type_error)
unset(_horde_rt_android_codes_type_error)
unset(_horde_rt_android_codes_type)
unset(_horde_rt_active_map_assignments)
unset(_horde_rt_active_map_assignment_count)
unset(_horde_rt_map_value_type_error)
unset(_horde_rt_map_value_type)
unset(_horde_rt_map_error)
