# Exact build policy for the isolated frozen-raygen provider.  This module owns
# no Vulkan state and must remain independent of per-frame renderer controls.
set(HORDE_RT_INSTRUMENTATION_OVERRIDE "" CACHE STRING "Exact RT instrumentation override (Shipping or Diagnostic)")
set(HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE "" CACHE STRING "Exact RT dielectric quality override (Mobile or High)")

function(horde_rt_validate_raygen_policy)
    set(_has_instrumentation FALSE)
    set(_has_quality FALSE)
    if(NOT "${HORDE_RT_INSTRUMENTATION_OVERRIDE}" STREQUAL "")
        set(_has_instrumentation TRUE)
    endif()
    if(NOT "${HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE}" STREQUAL "")
        set(_has_quality TRUE)
    endif()
    if(NOT _has_instrumentation AND NOT _has_quality)
        return()
    endif()
    if(NOT _has_instrumentation OR NOT _has_quality)
        message(FATAL_ERROR "HORDE_RT_INSTRUMENTATION_OVERRIDE and HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE must be supplied together.")
    endif()
    if(NOT ("${HORDE_RT_INSTRUMENTATION_OVERRIDE}" STREQUAL "Shipping" OR "${HORDE_RT_INSTRUMENTATION_OVERRIDE}" STREQUAL "Diagnostic"))
        message(FATAL_ERROR "HORDE_RT_INSTRUMENTATION_OVERRIDE must be exactly Shipping or Diagnostic.")
    endif()
    if(NOT ("${HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE}" STREQUAL "Mobile" OR "${HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE}" STREQUAL "High"))
        message(FATAL_ERROR "HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE must be exactly Mobile or High.")
    endif()
endfunction()

function(horde_rt_apply_raygen_policy target_name platform_name)
    horde_rt_validate_raygen_policy()
    if(NOT platform_name STREQUAL "Windows" AND NOT platform_name STREQUAL "Android")
        message(FATAL_ERROR "Unknown RT raygen policy platform: ${platform_name}")
    endif()
    if(NOT "${HORDE_RT_INSTRUMENTATION_OVERRIDE}" STREQUAL "")
        if(HORDE_RT_INSTRUMENTATION_OVERRIDE STREQUAL "Shipping")
            set(_instrumentation 0)
        else()
            set(_instrumentation 1)
        endif()
        if(HORDE_RT_DIELECTRIC_QUALITY_OVERRIDE STREQUAL "Mobile")
            set(_quality 0)
        else()
            set(_quality 1)
        endif()
        target_compile_definitions(${target_name} PRIVATE
            HORDE_RT_SELECTED_INSTRUMENTATION=${_instrumentation}
            HORDE_RT_SELECTED_DIELECTRIC_QUALITY=${_quality})
        return()
    endif()
    if(platform_name STREQUAL "Android")
        if(NOT DEFINED HORDE_RT_ANDROID_DEFAULT_INSTRUMENTATION OR NOT DEFINED HORDE_RT_ANDROID_DEFAULT_DIELECTRIC_QUALITY)
            message(FATAL_ERROR "Android must explicitly pass both default RT raygen policy dimensions.")
        endif()
        if(HORDE_RT_ANDROID_DEFAULT_INSTRUMENTATION STREQUAL "Shipping")
            set(_instrumentation 0)
        elseif(HORDE_RT_ANDROID_DEFAULT_INSTRUMENTATION STREQUAL "Diagnostic")
            set(_instrumentation 1)
        else()
            message(FATAL_ERROR "HORDE_RT_ANDROID_DEFAULT_INSTRUMENTATION must be exactly Shipping or Diagnostic.")
        endif()
        if(HORDE_RT_ANDROID_DEFAULT_DIELECTRIC_QUALITY STREQUAL "Mobile")
            set(_quality 0)
        elseif(HORDE_RT_ANDROID_DEFAULT_DIELECTRIC_QUALITY STREQUAL "High")
            set(_quality 1)
        else()
            message(FATAL_ERROR "HORDE_RT_ANDROID_DEFAULT_DIELECTRIC_QUALITY must be exactly Mobile or High.")
        endif()
        target_compile_definitions(${target_name} PRIVATE
            HORDE_RT_SELECTED_INSTRUMENTATION=${_instrumentation}
            HORDE_RT_SELECTED_DIELECTRIC_QUALITY=${_quality})
        return()
    endif()
    target_compile_definitions(${target_name} PRIVATE
        "$<$<CONFIG:Debug>:HORDE_RT_SELECTED_INSTRUMENTATION=1>"
        "$<$<CONFIG:Debug>:HORDE_RT_SELECTED_DIELECTRIC_QUALITY=1>"
        "$<$<CONFIG:Release>:HORDE_RT_SELECTED_INSTRUMENTATION=0>"
        "$<$<CONFIG:Release>:HORDE_RT_SELECTED_DIELECTRIC_QUALITY=1>"
        "$<$<NOT:$<OR:$<CONFIG:Debug>,$<CONFIG:Release>>>:HORDE_RT_POLICY_UNSUPPORTED_CONFIGURATION=1>")
endfunction()
